# tmux-lives install/uninstall/status. All functions live here (one conf.d file
# per feature). No startup trigger — these are user-invoked commands.

function __tmux_lives_key --description 'Effective switcher key: VARNAME unset -> DEFAULT; set (even empty) -> its value'
    set -l name $argv[1]
    set -q $name; or begin; echo $argv[2]; return; end
    echo $$name
end

function __tmux_lives_render_fragment --description 'Emit the tmux.conf fragment (categorizer path + switcher key binds)'
    # $cat is interpolated unquoted into nested tmux+sh quote layers; assumes no spaces.
    set -l cat $argv[1]
    set -l pkey $argv[2]   # prefix-table key ('' = no prefix bind)
    set -l skey $argv[3]   # no-prefix/direct key ('' = no direct bind)
    set -l color $argv[4]  # ShellFish bar color baked into the client-attached hook ('' = none)
    set -l invert $argv[5]  # 1 = darker status bar; else lighter
    set -l baseline (__tmux_lives_baseline_path)
    set -l popup
    set -l menu
    if test -n "$pkey"
        set -a popup "    bind-key $pkey display-popup -E -w 80% -h 70% -- fish --no-config $cat popup '#{client_name}'"
        set -a menu  "    bind-key $pkey run-shell 'fish --no-config $cat menu'"
    end
    if test -n "$skey"
        set -a popup "    bind-key -n $skey display-popup -E -w 80% -h 70% -- fish --no-config $cat popup '#{client_name}'"
        set -a menu  "    bind-key -n $skey run-shell 'fish --no-config $cat menu'"
    end
    set -l f
    set -a f "# tmux-lives — managed fragment. Generated by 'tmux-lives setup'; edit the plugin, not this."
    set -a f "set -g @plugin 'tmux-plugins/tmux-resurrect'"
    set -a f "set -g @plugin 'tmux-plugins/tmux-continuum'"
    set -a f "set -g @resurrect-strategy-nvim 'session'"
    set -a f "set -g @resurrect-strategy-vim  'session'"
    set -a f "set -g @resurrect-capture-pane-contents 'on'"
    set -a f "set -g @continuum-save-interval '15'"
    set -a f "set -g status-interval 15"
    set -a f "# macOS reports claude's version-named binary (versions/X.Y.Z) as the window"
    set -a f "# command; show 'claude' for a version-like name, pass everything else through."
    set -a f "set -g automatic-rename-format '#{?pane_in_mode,[tmux],#{?#{m:*.*.*,#{pane_current_command}},claude,#{pane_current_command}}}#{?pane_dead,[dead],}'"
    # Source the user's general config (~/.tmux-lives.conf) if present — applies to every
    # client at load (and is re-sourced on non-ShellFish attach). It sets status-left, the
    # lengths, window-status styles, and overrides the @tmux_lives_status_right time below.
    set -a f "set -g @tmux_lives_status_right \"%-I:%M %p · %b %-d \""
    set -a f "if-shell '[ -f $baseline ]' 'source-file $baseline'"
    # status-right = the time format via #{T:@var} (so strftime applies) + our tick.
    # continuum prepends its autosave hook when TPM runs. The user's file sets only the
    # @var, never status-right, so a re-source can't wipe the tick/continuum.
    set -a f "set -g status-right \"#{T:@tmux_lives_status_right}#(fish --no-config $cat tick)\""
    set -l ss (__tmux_lives_derive_status $color $invert)
    test -n "$ss"; and set -a f "set -g status-style $ss"
    if test -n "$popup"
        set -a f "if-shell 'tmux list-commands 2>/dev/null | grep -q display-popup' {"
        set -a f $popup
        set -a f "} {"
        set -a f $menu
        set -a f "}"
    end
    set -a f "set-hook -g client-session-changed {"
    set -a f "    if-shell -F '#{m:shellfish-*,#{client_session}}' {"
    set -a f "        run-shell \"fish --no-config $cat commandeer '#{client_name}' '#{client_session}'\""
    set -a f "    }"
    set -a f "}"
    set -a f "set-hook -g client-attached {"
    set -a f "    run-shell \"fish --no-config $cat on-attach '#{client_pid}' '#{client_tty}' '$color'\""
    set -a f "}"
    set -a f "set -ga update-environment \"LC_TERMINAL\""
    set -a f "set -ga update-environment \"LC_TERMINAL_VERSION\""
    set -a f "# Load declared plugins via TPM (setup clones them); without this they are"
    set -a f "# present but never sourced — no resurrect save/restore, no continuum autosave."
    set -a f "run '~/.tmux/plugins/tpm/tpm'"
    printf '%s\n' $f
end

function __tmux_lives_save_unit_text --description 'systemd save-on-shutdown unit text'
    set -l user $argv[1]; set -l uid $argv[2]
    printf '%s\n' \
        "[Unit]" \
        "Description=Save user tmux sessions (resurrect) before shutdown" \
        "DefaultDependencies=no" "Before=shutdown.target" \
        "After=user@$uid.service" "Conflicts=shutdown.target" "" \
        "[Service]" "Type=oneshot" "RemainAfterExit=yes" "ExecStart=/usr/bin/true" \
        "ExecStop=/usr/bin/su - $user -c 'tmux run-shell ~/.tmux/plugins/tmux-resurrect/scripts/save.sh'" "" \
        "[Install]" "WantedBy=multi-user.target"
end

function __tmux_lives_restore_unit_text --description 'systemd restore-at-boot unit text'
    set -l user $argv[1]; set -l uid $argv[2]
    printf '%s\n' \
        "[Unit]" "Description=Restore user tmux sessions (resurrect) at boot" \
        "After=multi-user.target user@$uid.service" "" \
        "[Service]" "Type=oneshot" \
        "ExecStart=/usr/bin/su - $user -c 'fish -c __tmux_restore'" "" \
        "[Install]" "WantedBy=multi-user.target"
end

function __tmux_lives_ensure_source_line --description 'Idempotently source the fragment before the TPM run-line'
    set -l tmux_conf $argv[1]; set -l fragment $argv[2]
    set -l line "source-file $fragment"
    test -f $tmux_conf; or touch $tmux_conf
    grep -qF -- "$line" $tmux_conf; and return 0
    if grep -q "tpm/tpm" $tmux_conf
        set -l tmp (mktemp)
        awk -v L="$line" '/tpm\/tpm/ && !d {print L; d=1} {print}' $tmux_conf > $tmp
        mv $tmp $tmux_conf
    else
        printf '%s\n' "$line" >> $tmux_conf
    end
end

function __tmux_lives_persistence_note --description 'macOS/non-systemd persistence model (for tmux-lives setup)'
    echo "no systemd — persistence via continuum autosave + restore on first SSH login"
end

function __tmux_lives_persistence_status --description 'macOS/non-systemd persistence status line'
    echo "OK persistence via continuum autosave + first-access restore"
end

function __tmux_lives_reload --description 'source the tmux config into a running server (no-op if none)'
    set -l conf $argv[1]
    test -n "$conf"; or set conf "$HOME/.tmux.conf"
    # No server yet (fresh host): nothing to reload — the fragment loads when tmux starts.
    tmux list-sessions >/dev/null 2>&1; or return 0
    tmux source-file "$conf" 2>/dev/null
end

function __tmux_lives_write_fragment --description 'Render the managed fragment, wire ~/.tmux.conf, reload tmux'
    set -l cat "$__fish_config_dir/functions/tmux-categorize.fish"
    set -l tmuxdir "$HOME/.config/tmux"
    set -l fragment "$tmuxdir/tmux-lives.conf"
    mkdir -p $tmuxdir
    __tmux_lives_render_fragment $cat (__tmux_lives_key tmux_lives_prefix_key S) (__tmux_lives_key tmux_lives_switcher_key M-s) (__tmux_lives_key tmux_lives_bar_color '') (__tmux_lives_key tmux_lives_status_invert 0) > $fragment
    __tmux_lives_ensure_source_line "$HOME/.tmux.conf" $fragment
    __tmux_lives_reload
end

function __tmux_lives_setup --description 'tmux-lives: install fragment + tmux.conf wiring + TPM plugins + systemd units'
    set -l tmuxdir "$HOME/.config/tmux"
    set -l fragment "$tmuxdir/tmux-lives.conf"

    set -l tpm "$HOME/.tmux/plugins/tpm"
    test -d $tpm; or git clone -q https://github.com/tmux-plugins/tpm $tpm
    for p in tmux-resurrect tmux-continuum
        set -l d "$HOME/.tmux/plugins/$p"
        test -d $d; or git clone -q https://github.com/tmux-plugins/$p $d
    end
    echo "tmux-lives setup: TPM + resurrect + continuum present"

    __tmux_lives_write_fragment
    echo "tmux-lives setup: wrote $fragment"
    echo "tmux-lives setup: ensured source-file line in ~/.tmux.conf"

    __tmux_lives_seed_baseline (__tmux_lives_baseline_path)
    echo "tmux-lives setup: baseline file at "(__tmux_lives_baseline_path)" (edit: tmux-lives setup conf edit)"

    if type -q systemctl
        set -l user (id -un); set -l uid (id -u)
        echo "tmux-lives setup: installing systemd units (sudo required)…"
        __tmux_lives_save_unit_text $user $uid | sudo tee /etc/systemd/system/tmux-resurrect-save.service >/dev/null
        __tmux_lives_restore_unit_text $user $uid | sudo tee /etc/systemd/system/tmux-resurrect-restore.service >/dev/null
        sudo systemctl daemon-reload
        sudo systemctl enable --now tmux-resurrect-save.service
        sudo systemctl enable tmux-resurrect-restore.service
        echo "tmux-lives setup: systemd units installed + enabled"
    else
        echo "tmux-lives setup: "(__tmux_lives_persistence_note)
    end
    set -l had_server 0
    tmux list-sessions >/dev/null 2>&1; and set had_server 1
    if test $had_server -eq 1
        echo "tmux-lives setup: done — reloaded the running tmux; the switcher + persistence are live now."
    else
        echo "tmux-lives setup: done — start tmux to load the fragment."
    end
    echo "tmux-lives setup: run 'tmux-lives setup verify' anytime to check the install."
end

function __tmux_lives_remove_source_line --description 'Remove the fragment source-file line'
    set -l tmux_conf $argv[1]; set -l fragment $argv[2]
    test -f $tmux_conf; or return 0
    set -l tmp (mktemp)
    grep -vF -- "source-file $fragment" $tmux_conf > $tmp
    mv $tmp $tmux_conf
end

function __tmux_lives_teardown --description 'tmux-lives: remove fragment + tmux.conf wiring + systemd units'
    set -l fragment "$HOME/.config/tmux/tmux-lives.conf"
    __tmux_lives_remove_source_line "$HOME/.tmux.conf" $fragment
    rm -f $fragment
    echo "tmux-lives teardown: removed fragment + source-file line"
    if type -q systemctl
        echo "tmux-lives teardown: removing systemd units (sudo)…"
        sudo systemctl disable --now tmux-resurrect-save.service 2>/dev/null
        sudo systemctl disable tmux-resurrect-restore.service 2>/dev/null
        sudo rm -f /etc/systemd/system/tmux-resurrect-{save,restore}.service
        sudo systemctl daemon-reload
        echo "tmux-lives teardown: systemd units removed"
    end
    echo "tmux-lives teardown: done. (TPM plugins under ~/.tmux/plugins left in place.)"
end

function __tmux_lives_status_lines --description 'One status line per tmux-lives layer'
    set -l cat "$__fish_config_dir/functions/tmux-categorize.fish"
    set -l fragment "$HOME/.config/tmux/tmux-lives.conf"
    set -l r
    test -f "$__fish_config_dir/conf.d/tmux.fish"; and set -a r "OK conf.d/tmux.fish deployed"; or set -a r "MISSING conf.d/tmux.fish (fisher install …)"
    test -f $cat; and set -a r "OK categorizer deployed"; or set -a r "MISSING categorizer"
    test -f $fragment; and set -a r "OK tmux fragment present"; or set -a r "MISSING tmux fragment (run tmux-lives setup)"
    grep -qF -- "source-file $fragment" "$HOME/.tmux.conf" 2>/dev/null; and set -a r "OK ~/.tmux.conf sources fragment"; or set -a r "MISSING source-file line"
    test -d "$HOME/.tmux/plugins/tmux-resurrect"; and set -a r "OK tmux-resurrect present"; or set -a r "MISSING tmux-resurrect"
    if type -q systemctl
        systemctl is-enabled tmux-resurrect-save.service >/dev/null 2>&1; and set -a r "OK save service enabled"; or set -a r "MISSING save service (run tmux-lives setup)"
    else
        set -a r (__tmux_lives_persistence_status)
    end
    set -l pk (__tmux_lives_key tmux_lives_prefix_key S); test -n "$pk"; or set pk '(off)'
    set -l sk (__tmux_lives_key tmux_lives_switcher_key M-s); test -n "$sk"; or set sk '(off)'
    set -a r "OK switcher keys: prefix=$pk  no-prefix=$sk"
    set -l bc (__tmux_lives_key tmux_lives_bar_color ''); test -n "$bc"; or set bc '(none)'
    if test "$bc" = '(none)'
        set -a r "OK bar color: $bc"
    else
        set -l bdir lighter; test (__tmux_lives_key tmux_lives_status_invert 0) = 1; and set bdir darker
        set -a r "OK bar color: $bc (status bar: $bdir)"
    end
    set -l bf (__tmux_lives_baseline_path)
    test -e $bf; and set -a r "OK baseline $bf present"; or set -a r "OK baseline $bf (none yet)"
    printf '%s\n' $r
end

function __tmux_lives_help_hint --description 'Pointer to the tmux-lives help command'
    echo 'Run `tmux-lives` to see all commands.'
end

function __tmux_lives_box --argument-names title --description 'frame stdin lines in a rounded, orange-bordered box titled <title>'
    set -l ORG (printf '\e[38;5;208m')
    set -l RST (printf '\e[0m')
    set -l lines
    while read -l l
        set -a lines "$l"
    end
    # content-field width = widest line, measured in DISPLAY columns; at least wide
    # enough for the title that sits in the top edge
    set -l cw 0
    for l in $lines
        set -l w (string length --visible -- "$l")
        test $w -gt $cw; and set cw $w
    end
    set -l tw (string length --visible -- "$title")
    set -l tmin (math "$tw + 2")
    test $tmin -gt $cw; and set cw $tmin
    # top edge:  ╭─ <title> ─…─╮   (frame orange, title in the default fg)
    printf '%s╭─ %s%s%s %s╮%s\n' $ORG $RST "$title" $ORG (string repeat -n (math "$cw - $tw - 1") ─) $RST
    # content rows:  │ <line padded to cw> │
    # NB: pad goes through a quoted var — an inline (string repeat -n 0 …) yields ZERO
    # args (not one empty string), which would shift the trailing printf args.
    for l in $lines
        set -l pad (string repeat -n (math "$cw - "(string length --visible -- "$l")) ' ')
        printf '%s│%s %s%s %s│%s\n' $ORG $RST "$l" "$pad" $ORG $RST
    end
    # bottom edge:  ╰─…─╯
    printf '%s╰%s╯%s\n' $ORG (string repeat -n (math "$cw + 2") ─) $RST
end

function __tmux_lives_help_lines --description 'tmux-lives help content (unframed; alias-first columns)'
    printf '%s\n' \
        'categorized tmux sessions, switcher & persistence' \
        '' \
        'USAGE' \
        '  tmux-lives <command> [options]' \
        ''
    # alias-first rows — printf field widths align the columns (alias 2, command+args 28).
    # close keeps its `q` alias in the dispatcher but the help shows only `x`.
    printf '%-2s%-28s%s\n' '' 'setup <command> [options]' 'run `tmux-lives setup -h` for details'
    printf '%-2s%-28s%s\n' '' '' 'install · verify · teardown · keys · auto'
    printf '%-2s%-28s%s\n' u 'update' 'update the plugin (fisher update)'
    echo ''
    printf '%-2s%-28s%s\n' n 'new [name]' 'create a new session (optional name)'
    printf '%-2s%-28s%s\n' a 'attach <name> [-t]' 'attach to a session (-t takes it)'
    printf '%-2s%-28s%s\n' p 'picker [-t]' 'open the session switcher (-t takes it)'
    printf '%-2s%-28s%s\n' f 'fix' 'repair the SSH agent socket'
    printf '%-2s%-28s%s\n' c 'categorize' 're-categorize sessions (fix a bad name)'
    printf '%-2s%-28s%s\n' '' 'clear [-q|-x]' 'kill idle sessions (-q/-x also exits)'
    printf '%-2s%-28s%s\n' x 'close' 'kill the current session and exit'
end

function __tmux_lives_help --description 'tmux-lives command list'
    __tmux_lives_help_lines | __tmux_lives_box 'tmux-lives'
end

function __tmux_lives_keys_cmd --description 'tmux-lives setup keys [-p K] [-s K]'
    if test (count $argv) -eq 0
        echo "switcher keys: prefix="(__tmux_lives_key tmux_lives_prefix_key S)"  no-prefix="(__tmux_lives_key tmux_lives_switcher_key M-s)
        return 0
    end
    set -l changed 0
    while test (count $argv) -ge 2
        switch $argv[1]
            case -p --prefix-key
                set -U tmux_lives_prefix_key $argv[2]; set changed 1; set -e argv[1..2]
            case -s --switcher-key
                set -U tmux_lives_switcher_key $argv[2]; set changed 1; set -e argv[1..2]
            case '*'
                echo "tmux-lives setup keys: unknown option '$argv[1]'" >&2; return 1
        end
    end
    if test (count $argv) -gt 0
        echo "tmux-lives setup keys: incomplete option '$argv[1]'" >&2; return 1
    end
    test $changed -eq 1; and __tmux_lives_write_fragment
end

function __tmux_lives_derive_status --description 'css color + invert(0/1) -> "bg=#rrggbb,fg=#rrggbb" for status-style; empty if unparseable'
    set -l color (string lower -- $argv[1])
    set -l invert $argv[2]
    test -n "$color"; or return
    set -l r; set -l g; set -l b
    set -l m (string match -rg '^#([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$' -- $color)
    if test (count $m) -eq 3
        set r (math "0x$m[1]"); set g (math "0x$m[2]"); set b (math "0x$m[3]")
    else
        set m (string match -rg '^#([0-9a-f])([0-9a-f])([0-9a-f])$' -- $color)
        if test (count $m) -eq 3
            set r (math "0x$m[1]$m[1]"); set g (math "0x$m[2]$m[2]"); set b (math "0x$m[3]$m[3]")
        else
            set m (string match -rg '^rgba?\(\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)' -- $color)
            if test (count $m) -eq 3
                set r $m[1]; set g $m[2]; set b $m[3]
            else
                return
            end
        end
    end
    # clamp 0-255
    for v in r g b
        set -l x $$v
        test "$x" -gt 255; and set $v 255
    end
    if test "$invert" = 1
        set r (math "round($r * 0.75)"); set g (math "round($g * 0.75)"); set b (math "round($b * 0.75)")
    else
        set r (math "round($r + (255 - $r) * 0.25)"); set g (math "round($g + (255 - $g) * 0.25)"); set b (math "round($b + (255 - $b) * 0.25)")
    end
    set -l hex (printf '#%02x%02x%02x' $r $g $b)
    # Tinted text (Light tint f=0.68): a hex shade of the bar's own hue, blended toward
    # white (dark bar) or black (light bar). Palette-independent; visible hue, still clearly
    # light/dark. fish `math` has no comparison operators -> integer luminance + test.
    set -l L (math "round(0.299 * $r + 0.587 * $g + 0.114 * $b)")
    set -l tr; set -l tg; set -l tb
    if test $L -gt 140
        set tr (math "round($r * 0.32)"); set tg (math "round($g * 0.32)"); set tb (math "round($b * 0.32)")
    else
        set tr (math "round($r + (255 - $r) * 0.68)"); set tg (math "round($g + (255 - $g) * 0.68)"); set tb (math "round($b + (255 - $b) * 0.68)")
    end
    echo "bg=$hex,fg="(printf '#%02x%02x%02x' $tr $tg $tb)
end

function __tmux_lives_color_cmd --description 'tmux-lives setup color [<css-color>] [-i|--invert]: ShellFish tab color + derived status bar'
    set -l invert 0
    set -l color
    set -l have_color 0
    for a in $argv
        switch $a
            case -i --invert
                set invert 1
            case '*'
                set color $a; set have_color 1
        end
    end
    if test (count $argv) -eq 0
        set -l c (__tmux_lives_key tmux_lives_bar_color '')
        set -l dir lighter; test (__tmux_lives_key tmux_lives_status_invert 0) = 1; and set dir darker
        test -n "$c"; and echo "bar color: $c (status bar: $dir)"; or echo "bar color: (none)"
        return 0
    end
    if test $have_color -eq 0
        echo "tmux-lives setup color: -i needs a color, e.g. tmux-lives setup color \"#1f6feb\" -i" >&2
        return 1
    end
    if test -n "$color"; and string match -qr '[^A-Za-z0-9#(),./% -]' -- $color
        echo "tmux-lives setup color: invalid color '$color' — use a CSS color (red, #1f6feb, rgb(...), color(p3 ...))" >&2
        return 1
    end
    set -U tmux_lives_bar_color $color
    set -U tmux_lives_status_invert $invert
    __tmux_lives_write_fragment
    if test -n "$color"
        set -l dir lighter; test $invert -eq 1; and set dir darker
        echo "tmux-lives: bar color set to $color (ShellFish tab; status bar $dir)"
    else
        echo "tmux-lives: bar color cleared"
    end
end

function __tmux_lives_baseline_path --description 'path to the user-owned non-ShellFish baseline file (seam: tmux_lives_baseline_conf)'
    # Default mirrors __tcz_on_attach's baseline path in functions/tmux-categorize.fish — keep in sync.
    set -q tmux_lives_baseline_conf; and echo $tmux_lives_baseline_conf; or echo "$HOME/.tmux-lives.conf"
end

function __tmux_lives_baseline_template --description 'print the default ~/.tmux-lives.conf (status-bar polish + non-ShellFish baseline)'
    printf '%s\n' \
        '# ~/.tmux-lives.conf — your general tmux-lives config.' \
        '# Sourced when tmux-lives loads (every client) and re-applied when a NON-ShellFish' \
        "# client attaches. Edit freely; 'tmux-lives setup conf reset' restores these defaults." \
        '' \
        '# --- status bar ---' \
        'set -g status-left " ❯ #{session_name} "' \
        'set -g status-left-length 40' \
        'set -g status-right-length 60' \
        '# status-right content goes through this var so tmux-lives keeps the categorize tick' \
        '# + continuum autosave attached (it sets the actual status-right). 12h, month-first:' \
        'set -g @tmux_lives_status_right "%-I:%M %p · %b %-d "' \
        '# make the active window stand out' \
        'set -g window-status-format         " #I:#W#{?window_flags,#F, } "' \
        'set -g window-status-current-format " #I:#W#{?window_flags,#F, } "' \
        'set -g window-status-current-style  "bold"' \
        '' \
        '# --- non-ShellFish baseline (re-applied when a non-ShellFish client attaches) ---' \
        "# Settings ShellFish's integration forces that you want undone for other clients." \
        '# Example:' \
        '# set -g mouse off'
end

function __tmux_lives_seed_baseline --argument-names f --description 'create the baseline file from the template iff absent (never overwrites)'
    test -e $f; and return 0
    __tmux_lives_baseline_template > $f
end

function __tmux_lives_conf_source --argument-names f --description 'source the user conf into tmux (honors the tmux_lives_tmux_socket test seam)'
    if set -q tmux_lives_tmux_socket
        command tmux -L $tmux_lives_tmux_socket source-file $f 2>/dev/null
    else
        tmux source-file $f 2>/dev/null
    end
end

function __tmux_lives_conf_cmd --description 'tmux-lives setup conf [edit|add <tmux-command>|reset]: manage ~/.tmux-lives.conf'
    set -l f (__tmux_lives_baseline_path)
    switch "$argv[1]"
        case ''
            echo "baseline file: $f"
            if test -e $f
                cat $f
            else
                echo "(does not exist yet — run 'tmux-lives setup conf edit' to create it)"
            end
        case edit
            __tmux_lives_seed_baseline $f
            set -l ed $EDITOR
            test -n "$ed"; or set ed vi
            $ed $f
        case add
            if test (count $argv) -lt 2
                echo "usage: tmux-lives setup conf add <tmux-command>" >&2
                return 1
            end
            __tmux_lives_seed_baseline $f
            printf '%s\n' (string join ' ' $argv[2..]) >> $f
            __tmux_lives_conf_source $f
            echo "tmux-lives: added to $f"
        case reset
            set -l backed 0
            test -e $f; and cp $f "$f.bak"; and set backed 1
            __tmux_lives_baseline_template > $f
            __tmux_lives_conf_source $f
            if test $backed -eq 1
                echo "tmux-lives: restored defaults to $f (previous version saved to $f.bak)"
            else
                echo "tmux-lives: wrote default $f"
            end
        case '*'
            echo "tmux-lives setup conf: unknown option '$argv[1]'" >&2
            echo "usage: tmux-lives setup conf [edit|add <tmux-command>|reset]" >&2
            return 1
    end
end

function __tmux_lives_setup_help_lines --description 'tmux-lives setup help content (unframed; tightened to fit an 80-col frame)'
    printf '%s\n' \
        'install & configuration' \
        '' \
        'install, i                  wire ~/.tmux.conf + plugins (systemd on Linux)' \
        'verify, v                   check install health + switcher keys' \
        'teardown                    remove the wiring (plugin & TPM kept)' \
        'keys                        show the current switcher keys' \
        "  -p, --prefix-key <key>    prefix-table bind (default: S; '' off)" \
        "  -s, --switcher-key <key>  no-prefix bind (default: M-s = Opt+s; '' off)" \
        'auto on|off|toggle|status   auto-attach to tmux on SSH login' \
        'color [<css>] [-i]          ShellFish tab color (+ status bar; -i darker)' \
        'conf [edit|add|reset]       manage ~/.tmux-lives.conf (reset=defaults)'
end

function __tmux_lives_setup_help --description 'tmux-lives setup command list'
    __tmux_lives_setup_help_lines | __tmux_lives_box 'tmux-lives setup'
end

function __tmux_lives_setup_dispatch
    switch "$argv[1]"
        case '' help -h --help
            __tmux_lives_setup_help
        case install i
            __tmux_lives_setup
        case verify v
            echo "tmux-lives verify:"
            __tmux_lives_status_lines | sed 's/^/  /'
        case teardown
            __tmux_lives_teardown
        case keys
            __tmux_lives_keys_cmd $argv[2..]
        case color
            __tmux_lives_color_cmd $argv[2..]
        case conf
            __tmux_lives_conf_cmd $argv[2..]
        case auto
            __tmux_lives_auto $argv[2..]
        case '*'
            echo "tmux-lives setup: unknown command '$argv[1]'" >&2
            __tmux_lives_setup_help >&2
            return 1
    end
end

function __tmux_lives_digest --description 'cksum over the given files (tmux-lives update change-detection)'
    cat $argv 2>/dev/null | cksum
end

function __tmux_lives_update --description 'Update the tmux-lives plugin via fisher; stay quiet unless something changed'
    if not type -q fisher
        echo 'tmux-lives update: fisher not found — install fisher, or update manually' >&2
        return 1
    end
    # installed plugin files to watch for changes (overridable in tests)
    set -l files $tmux_lives_update_files
    test -n "$files"; or set files \
        $__fish_config_dir/conf.d/tmux.fish \
        $__fish_config_dir/conf.d/tmux-lives-install.fish \
        $__fish_config_dir/functions/tmux-categorize.fish
    set -l before (__tmux_lives_digest $files)
    # fisher reinstalls (and is noisy) on every update — divert its output to a file
    # (a redirect, NOT a `(…)` capture: that would break fisher's background-job fetch)
    # and only surface it if something actually changed, or if it failed.
    set -l log (mktemp)
    set -g _tmux_lives_updating 1   # silence the generic post-update note; we report below
    fisher update bit-saver/tmux-lives >$log 2>&1
    set -l rc $status
    set -e _tmux_lives_updating
    if test $rc -ne 0
        cat $log >&2                # surface fisher's error
        rm -f $log
        return $rc
    end
    if test "$before" = (__tmux_lives_digest $files)
        echo 'tmux-lives: already up to date.'
    else
        cat $log                    # release fisher's output — something changed
        echo 'tmux-lives: updated — run `exec fish` to load the new version.'
    end
    rm -f $log
end

function tmux-lives --description 'tmux-lives: unified command — setup/update/new/attach/picker/fix/clear/close'
    set -l cmd $argv[1]
    switch "$cmd"
        case '' help -h --help
            __tmux_lives_help
        case picker p
            __tmux_lives_picker $argv[2..]
        case attach a
            __tmux_lives_attach $argv[2..]
        case new n
            __tmux_lives_new $argv[2..]
        case close x q
            __tmux_lives_close
        case clear
            __tmux_lives_clear $argv[2..]
        case fix f
            __tmux_lives_fix
        case update u
            __tmux_lives_update
        case categorize c
            __tmux_categorize
        case setup
            __tmux_lives_setup_dispatch $argv[2..]
        case install i verify v teardown keys auto color conf
            # hidden shortcut: setup subcommands also work at top level (kept out of help)
            __tmux_lives_setup_dispatch $argv
        case '*'
            echo "tmux-lives: unknown command '$cmd'" >&2
            __tmux_lives_help >&2
            return 1
    end
end

function _tmux_lives_post_install --on-event tmux-lives-install_install --description 'Post-install guidance'
    printf '%s\n' \
        '✓ tmux-lives installed. One command finishes setup:' \
        '    tmux-lives setup install' \
        '  (wires tmux + plugins, then reloads tmux). '(__tmux_lives_help_hint)
end

function __tmux_lives_fragment_path --description 'path to the generated managed fragment (seam: tmux_lives_fragment_file)'
    set -q tmux_lives_fragment_file; and echo $tmux_lives_fragment_file; or echo "$HOME/.config/tmux/tmux-lives.conf"
end

function _tmux_lives_post_update --on-event tmux-lives-install_update --description 'Post-update: re-render the fragment (if set up) so new wiring lands, then note'
    # `fisher update` refreshes the plugin CODE but not the generated fragment. If this host
    # has been set up (the fragment exists), re-render it so new wiring (e.g. the client-attached
    # hook) lands without a manual `tmux-lives setup` — then reload tmux.
    set -l refreshed 0
    if test -e (__tmux_lives_fragment_path)
        __tmux_lives_write_fragment
        set refreshed 1
    end
    set -q _tmux_lives_updating; and return   # `tmux-lives update` reports the result itself
    if test $refreshed -eq 1
        printf '%s\n' '✓ tmux-lives updated — tmux config refreshed + reloaded; run `exec fish` for the new shell functions. '(__tmux_lives_help_hint)
    else
        printf '%s\n' '✓ tmux-lives updated — open a new shell (exec fish) to load it. '(__tmux_lives_help_hint)
    end
end
