# tmux-lives install/uninstall/status. All functions live here (one conf.d file
# per feature). No startup trigger — these are user-invoked commands.

# module-scope constant for the OKLCH conversion core below (__tmux_lives_rgb_to_oklch /
# __tmux_lives_oklch_to_linrgb use it for the atan2/cos/sin hue math).
set -q __tmux_lives_pi; or set -g __tmux_lives_pi (math "atan2(0, -1)")

function __tmux_lives_key --description 'Effective switcher key: VARNAME unset -> DEFAULT; set (even empty) -> its value'
    set -l name $argv[1]
    set -q $name; or begin; echo $argv[2]; return; end
    echo $$name
end

function __tmux_lives_render_fragment --description 'Emit the tmux.conf fragment (categorizer path + switcher key binds)'
    # $cat is interpolated unquoted into nested tmux+sh quote layers; assumes no spaces.
    set -l cat $argv[1]
    set -l pkey $argv[2]   # prefix-table key ('' = no prefix bind)
    set -l skey $argv[3]   # no-prefix/direct key ('' = no direct bind)
    set -l color $argv[4]  # ShellFish bar color baked into the client-attached hook ('' = none)
    set -l invert $argv[5]  # 1 = darker status bar; else lighter
    set -l modalkey $argv[6]   # root-table modal key ('' = no bind)
    set -l scratchkey $argv[7] # root-table scratch-toggle key ('' = no bind)
    set -l resizekey $argv[8]   # root-table scratch-resize-mode key ('' = no bind)
    set -l statusposkey $argv[9]   # root-table status-position toggle ('' = no bind)
    set -l statusviskey $argv[10]  # root-table status-visibility toggle ('' = no bind)
    set -l cursorstyle $argv[11]   # steady cursor-style (block|bar|underline) to stop the ShellFish cursor flicker; '' = leave tmux's default. See [[shellfish-cursor-flicker]].
    set -l themekey $argv[12]     # root-table theme-picker key ('' = no bind)
    set -l theme $argv[13]        # v5 relationship ('' or 'off' = legacy; write_fragment passes the effective default mono)
    set -l place $argv[14]        #   14 place       seed placement bar|tabs|cap ('' = bar)
    set -l mode $argv[15]         #   15 mode        literal|derived ('' = derived)
    set -l themephase $argv[16]   #   16 themephase  hue phase in degrees ('' = 0)
    set -l syncterm $argv[17]     #   17 syncterm    TERM glob told to use synchronized output ('' = off)
    test "$theme" = off; and set theme ''
    set -l baseline (__tmux_lives_baseline_path)
    set -l state (__tmux_lives_state_path)
    set -l popup
    set -l menu
    if test -n "$pkey"
        set -a popup "    bind-key $pkey display-popup -E -w 80% -h 70% -- fish --no-config $cat popup '#{client_name}'"
        set -a menu  "    bind-key $pkey run-shell 'fish --no-config $cat menu'"
    end
    if test -n "$skey"
        set -a popup "    bind-key -n $skey display-popup -E -w 80% -h 70% -- fish --no-config $cat popup '#{client_name}'"
        set -a menu  "    bind-key -n $skey run-shell 'fish --no-config $cat menu'"
    end
    if test -n "$modalkey"
        set -a popup "    bind-key -n $modalkey display-popup -B -E -w 34 -h 15 -- fish --no-config $cat modal '#{client_name}' '$modalkey' '$scratchkey' '$resizekey' '$skey'"
        set -a menu  "    bind-key -n $modalkey run-shell 'fish --no-config $cat modal-menu'"
    end
    set -l f
    set -a f "# tmux-lives — managed fragment. Generated by 'tmux-lives setup'; edit the plugin, not this."
    set -a f "set -g @plugin 'tmux-plugins/tmux-resurrect'"
    set -a f "set -g @plugin 'tmux-plugins/tmux-continuum'"
    set -a f "set -g @resurrect-strategy-nvim 'session'"
    set -a f "set -g @resurrect-strategy-vim  'session'"
    set -a f "set -g @resurrect-capture-pane-contents 'on'"
    set -a f "set -g @continuum-save-interval '15'"
    set -a f "set -g status-interval 15"
    # Ported from tmux-sensible so it can be dropped. TPM loads plugins AFTER this
    # fragment, so sensible silently won every conflict — including overriding our
    # status-interval 15 with its own 5. escape-time is a SERVER option (-s): at the
    # default 500ms tmux swallows ESC long enough to lag vim and Claude's TUI.
    set -a f "set -s escape-time 0"
    set -a f "set -g focus-events on"
    # tmux's own default is 750ms, which flashes transient notices past unread —
    # including the M-r resize-mode hint this plugin emits with display-message.
    set -a f "set -g display-time 4000"
    # Pin a STEADY cursor so tmux's cstyle re-emission on redraw doesn't flicker the ShellFish
    # cursor (a steady style re-emitted is invisible). '' leaves tmux's default untouched.
    test -n "$cursorstyle"; and set -a f "set -g cursor-style $cursorstyle"
    # The OTHER ShellFish cursor fix. tmux picks, per client and only at attach, whether a
    # terminal can buffer synchronized output — from its own terminal identification, never
    # by asking the client. It knows Ghostty; it does not know ShellFish. So it wrote each
    # of Claude's frames unwrapped and ShellFish painted every intermediate state, ~21 cursor
    # hide/show pairs a second. ShellFish DOES implement DECSET 2026 — tmux simply never
    # finds out — so we tell it. Gated to tmux >= 3.7 for two independent reasons: only there
    # does this capability map to DECSET 2026 (3.3a emits the older iTerm2 DCS form, which we
    # have no evidence ShellFish reads), and only there can the bug exist at all, since older
    # tmux never answers the DECRQM query so Claude never enables sync. sort -V keeps 3.10 >
    # 3.7, which a numeric compare would get wrong. See [[shellfish-cursor-flicker]].
    set -l syncgate 'v=$(tmux -V | tr -dc 0-9.); test $(echo $v 3.7 | tr " " "\n" | sort -V | head -n1) = 3.7'
    test -n "$syncterm"; and set -a f "if-shell '$syncgate' \"set -as terminal-features '$syncterm:sync'\""
    set -a f "# macOS reports claude's version-named binary (versions/X.Y.Z) as the window"
    set -a f "# command; show 'claude' for a version-like name, pass everything else through."
    set -a f "set -g automatic-rename-format '#{?pane_in_mode,[tmux],#{?#{m:*.*.*,#{pane_current_command}},claude,#{pane_current_command}}}#{?pane_dead,[dead],}'"
    # Source the user's general config (~/.tmux-lives.conf) if present — applies to every
    # client at load (and is re-sourced on non-ShellFish attach). The baseline sets the clock
    # @var (@tmux_lives_status_right) + status-right-length; layout (window list, identity, caps) now lives in status-format[0] below.
    set -a f "set -g @tmux_lives_status_right \"%-I:%M %p · %b %-d \""
    set -a f "if-shell '[ -f $baseline ]' 'source-file $baseline'"
    # status-right = the time format via #{T:@var} (so strftime applies) + our tick.
    # It is INSTALLED, not assigned: a bare `set -g status-right` discards whatever is
    # already there, and tmux-continuum schedules its autosave by PREPENDING
    # #(continuum_save.sh) — the bar's refresh IS its scheduler, no daemon, no timer. So
    # overwriting the option stops session snapshots permanently and silently (observed
    # on macwork: 52h with no autosave across ten live sessions).
    # Recovery used to be accidental: this fragment emits the tpm run-line AFTER this
    # point, so tpm re-sourced continuum.tmux and it re-prepended itself. That repair is
    # skipped entirely whenever continuum's own `another_tmux_server_running` guard trips,
    # which is how macwork lost it for 52h. Merge instead of assign, and depend on nobody.
    # Plain run-shell (no -b) is SYNCHRONOUS in tmux 3.3a — verified — so the value is in
    # place before the fragment finishes sourcing.
    set -a f "run-shell \"fish --no-config $cat status-right-install '$color'\""
    # --- theme engine v5 (relationship curve): with a relationship in argv[13] the whole bar
    # renders from the 7-role gradient palette (bar sep tabs active windows cap text) via
    # __tmux_lives_theme_palette (seed + relationship/place/mode/phase); otherwise the v2
    # path is unchanged.
    set -l tpal
    # declared OUTSIDE the if: fish's `set -l` scopes to the enclosing BLOCK (if/for/while),
    # not just the function — a `set -l` inside the `if` below would go out of scope at its
    # `end`, well before the themed branch (~L123) that needs it for @tmux_lives_mark_fg.
    set -l seedhex
    if test -n "$theme"
        set seedhex (__tmux_lives_seed_hex $color)
        test -n "$seedhex"; and set tpal (__tmux_lives_theme_palette $seedhex "$theme" "$place" "$mode" "$themephase")
    end
    set -l themed 0
    test (count $tpal) -eq 7; and set themed 1
    if test $themed -eq 1
        # bar = per-scheme recipe cell on seed's depth row (mono: seed); windows = accent-ring sample
        set -a f "set -g status-style bg=$tpal[1],fg=$tpal[5]"
    else
        set -l ss (__tmux_lives_derive_status $color $invert)
        test -n "$ss"; and set -a f "set -g status-style $ss"
    end
    # --- status bar overhaul: names-only window list, @option-driven caps, status-format[0] ---
    # Layout lives in status-format[0] (built by the categorizer's pure `status-format` verb);
    # every knob is a live-tunable @option so `tmux set -g @tmux_lives_*` retints with no re-render.
    # claude windows render like any other (coloring removed 2026-07-21; the ✦ presence mark remains)
    set -a f "set -g window-status-format '#W'"
    # picker-legibility-autoapply Task 6: active was computed on every apply
    # and pushed to @tmux_lives_active_fg, but nothing read it — it rendered
    # nowhere in any session. The current window is exactly what it was
    # evidently meant to colour; text_fg keeps its own consumer (centre
    # identity, below).
    set -a f "set -g window-status-current-format '#[bold]#[fg=#{@tmux_lives_active_fg}]#W#[fg=default]#[nobold]'"
    set -a f "set -g window-status-separator ' #[fg=#{@tmux_lives_sep_fg}]•#[fg=default] '"
    # cap/accent colors. Themed: bar/cap are gradient samples. Legacy (theme off / no usable
    # seed): bar bg = the ShellFish-derived status bg; the cap is a flat neutral (the v2
    # geometric-harmony engine that used to pick a role color here is gone).
    set -l barbg
    set -l capbg
    if test $themed -eq 1
        set barbg $tpal[1]
        set capbg $tpal[6]
    else
        set barbg (__tmux_lives_derive_status_bg $color $invert)   # the bar's own bg (status-style bg)
        test -n "$barbg"; or set barbg colour236
        set capbg colour238   # legacy neutral cap (theme off / no usable seed)
    end
    set -l capfg (__tmux_lives_contrast_fg $capbg)                # readable fg for whichever cap shade/hue was picked
    # QUOTE the values: an unquoted #rrggbb hex is read as a tmux COMMENT (option set to empty). Single
    # quotes keep the '#5793f0' bg intact (harmless around the colourNNN default too).
    set -a f "set -g @tmux_lives_bar_bg '$barbg'"                 # slant transition target (cap -> bar)
    set -a f "set -g @tmux_lives_cap_bg '$capbg'"
    set -a f "set -g @tmux_lives_cap_fg '$capfg'"
    if test $themed -eq 1
        set -a f "set -g @tmux_lives_sep_fg '$tpal[2]'"           # sep = accent-ring sample; the • separators
        set -a f "set -g @tmux_lives_tabs_color '$tpal[3]'"       # tabs = kin of bar+cap (v3.3); Phase 2 wires ShellFish OSC
        set -a f "set -g @tmux_lives_active_fg '$tpal[4]'"        # active = accent-ring sample; the current window's name
        set -a f "set -g @tmux_lives_mark_fg '$seedhex'"          # the ✦ mark = the seed's home base
        set -a f "set -g @tmux_lives_text_fg '$tpal[7]'"          # text = the bar's contrast side; centre identity
    else
        set -a f "set -g @tmux_lives_sep_fg default"
        set -a f "set -g @tmux_lives_tabs_color ''"
        set -a f "set -g @tmux_lives_active_fg default"
        set -a f "set -g @tmux_lives_mark_fg default"
        set -a f "set -g @tmux_lives_text_fg default"
    end
    set -a f "set -g @tmux_lives_prefix_color colour214"
    set -a f "set -g @tmux_lives_resize_color colour208"
    set -a f "set -g @tmux_lives_heal_interval 120"        # color-only self-heal backstop seconds (0 = off)
    set -a f "set -g @tmux_lives_glyph_remote '"(printf '\U0000eb3a')"'"   # cod-remote
    set -a f "set -g @tmux_lives_glyph_local '"(printf '\U0000ea7a')"'"    # cod-vm
    # host-kind + status-format are computed at RENDER time by the categorizer (pure verbs).
    # Compute into a pre-declared var FIRST: a bad/absent $cat (e.g. a test's fake path) makes
    # the substitution fail, which would skip an inline `set -a f "..."(…)` statement entirely
    # (a broken fragment). This form leaves the var empty so the option line is still emitted
    # (empty value). 2>/dev/null keeps a bad path from leaking "No such file" to stderr.
    set -l hostkind ""; set hostkind (fish --no-config $cat host-kind 2>/dev/null)
    set -l sfmt ""; set sfmt (fish --no-config $cat status-format 2>/dev/null)
    set -a f "set -g @tmux_lives_host_kind '$hostkind'"
    set -a f "set -g @tmux_lives_claude ''"
    set -a f "set -g status-format[0] \"$sfmt\""
    # reapply the persisted status-position/visibility (written by the C-M-a/C-M-s toggles)
    set -a f "if-shell '[ -f $state ]' 'source-file $state'"
    if test -n "$popup"
        set -a f "if-shell 'tmux list-commands 2>/dev/null | grep -q display-popup' {"
        set -a f $popup
        set -a f "} {"
        set -a f $menu
        set -a f "}"
    end
    test -n "$scratchkey"; and set -a f "bind-key -n $scratchkey run-shell 'fish --no-config $cat scratch'"
    test -n "$themekey"; and set -a f "bind-key -n $themekey display-popup -B -E -w 52 -h 85% -- fish --no-config $cat theme-picker '#{client_name}'"
    if test -n "$resizekey"
        set -a f "bind-key -n $resizekey run-shell \"fish --no-config $cat resize-enter '#{client_name}'\""
        set -a f "bind-key -T tmuxlives-resize Left  { run-shell \"fish --no-config $cat scratch-resize L\" ; switch-client -T tmuxlives-resize }"
        set -a f "bind-key -T tmuxlives-resize Right { run-shell \"fish --no-config $cat scratch-resize R\" ; switch-client -T tmuxlives-resize }"
        set -a f "bind-key -T tmuxlives-resize Up    { run-shell \"fish --no-config $cat scratch-resize U\" ; switch-client -T tmuxlives-resize }"
        set -a f "bind-key -T tmuxlives-resize Down  { run-shell \"fish --no-config $cat scratch-resize D\" ; switch-client -T tmuxlives-resize }"
        set -a f "bind-key -T tmuxlives-resize h     { run-shell \"fish --no-config $cat scratch-orient h\" ; switch-client -T tmuxlives-resize }"
        set -a f "bind-key -T tmuxlives-resize w     { run-shell \"fish --no-config $cat scratch-orient w\" ; switch-client -T tmuxlives-resize }"
        set -a f "bind-key -T tmuxlives-resize x       run-shell \"fish --no-config $cat scratch-kill\""
        set -a f "bind-key -T tmuxlives-resize Escape  switch-client -T root"
        set -a f "bind-key -T tmuxlives-resize Enter   switch-client -T root"
    end
    test -n "$statusposkey"; and set -a f "bind-key -n $statusposkey run-shell 'fish --no-config $cat status-pos-toggle'"
    test -n "$statusviskey"; and set -a f "bind-key -n $statusviskey run-shell 'fish --no-config $cat status-vis-toggle'"
    set -a f "set-hook -g client-session-changed {"
    set -a f "    run-shell \"fish --no-config $cat retitle\""
    set -a f "    if-shell -F '#{m:shellfish-*,#{client_session}}' {"
    set -a f "        run-shell \"fish --no-config $cat commandeer '#{client_name}' '#{client_session}'\""
    set -a f "    }"
    set -a f "}"
    set -a f "set-hook -g client-attached {"
    set -a f "    run-shell \"fish --no-config $cat on-attach '#{client_pid}' '#{client_tty}' '$color'\""
    set -a f "}"
    # `set -ga` appends UNCONDITIONALLY and this fragment is re-sourced on every reload,
    # so a bare append grows without bound — 54 copies of each name observed on a host
    # with ~18 days of uptime. Guard each: append only when absent.
    # `show -gv update-environment` prints ONE NAME PER LINE (it is an array option), so
    # `grep -qx` is the exact test — and -x is load-bearing, since a substring match would
    # let LC_TERMINAL_VERSION satisfy the LC_TERMINAL check and silently drop it.
    # FAIL CLOSED: capture first and `&&`. A bare `! tmux show … | grep -qx X` takes the
    # PIPELINE's status, which is grep's 1 when tmux is unreachable — the `!` flips that
    # to true and the unbounded growth comes straight back, silently. With `&&`, a failed
    # `show` short-circuits to status 1 and nothing is appended.
    for uev in LC_TERMINAL LC_TERMINAL_VERSION
        set -a f "if-shell 'ue=\$(tmux show -gv update-environment) && ! printf \"%s\\n\" \"\$ue\" | grep -qx $uev' 'set -ga update-environment \"$uev\"'"
    end
    set -a f "# Load declared plugins via TPM (setup clones them); without this they are"
    set -a f "# present but never sourced — no resurrect save/restore, no continuum autosave."
    set -a f "run '~/.tmux/plugins/tpm/tpm'"
    printf '%s\n' $f
end

function __tmux_lives_save_unit_text --description 'systemd save-on-shutdown unit text'
    set -l user $argv[1]; set -l uid $argv[2]
    printf '%s\n' \
        "[Unit]" \
        "Description=Save user tmux sessions (resurrect) before shutdown" \
        "DefaultDependencies=no" "Before=shutdown.target" \
        "After=user@$uid.service" "Conflicts=shutdown.target" "" \
        "[Service]" "Type=oneshot" "RemainAfterExit=yes" "ExecStart=/usr/bin/true" \
        "ExecStop=/usr/bin/su - $user -c 'tmux run-shell ~/.tmux/plugins/tmux-resurrect/scripts/save.sh'" "" \
        "[Install]" "WantedBy=multi-user.target"
end

function __tmux_lives_restore_unit_text --description 'systemd restore-at-boot unit text'
    set -l user $argv[1]; set -l uid $argv[2]
    printf '%s\n' \
        "[Unit]" "Description=Restore user tmux sessions (resurrect) at boot" \
        "After=multi-user.target user@$uid.service" "" \
        "[Service]" "Type=oneshot" \
        "ExecStart=/usr/bin/su - $user -c 'fish -c __tmux_restore'" "" \
        "[Install]" "WantedBy=multi-user.target"
end

function __tmux_lives_ensure_source_line --description 'Idempotently source the fragment before the TPM run-line'
    set -l tmux_conf $argv[1]; set -l fragment $argv[2]
    set -l line "source-file $fragment"
    test -f $tmux_conf; or touch $tmux_conf
    grep -qF -- "$line" $tmux_conf; and return 0
    if grep -q "tpm/tpm" $tmux_conf
        set -l tmp (mktemp)
        awk -v L="$line" '/tpm\/tpm/ && !d {print L; d=1} {print}' $tmux_conf > $tmp
        mv $tmp $tmux_conf
    else
        printf '%s\n' "$line" >> $tmux_conf
    end
end

function __tmux_lives_persistence_note --description 'macOS/non-systemd persistence model (for tmux-lives setup)'
    echo "no systemd — persistence via continuum autosave + restore on first SSH login"
end

function __tmux_lives_persistence_status --description 'macOS/non-systemd persistence status line'
    echo "OK persistence via continuum autosave + first-access restore"
end

function __tmux_lives_reload --description 'source the tmux config into a running server (no-op if none)'
    set -l conf $argv[1]
    test -n "$conf"; or set conf "$HOME/.tmux.conf"
    # No server yet (fresh host): nothing to reload — the fragment loads when tmux starts.
    tmux list-sessions >/dev/null 2>&1; or return 0
    tmux source-file "$conf" 2>/dev/null
end

function __tmux_lives_write_fragment --description 'Render the managed fragment, wire ~/.tmux.conf, reload tmux'
    set -l cat "$__fish_config_dir/functions/tmux-categorize.fish"
    # Defense-in-depth: never render/wire/reload a fragment whose categorizer path
    # does not exist (e.g. a stray call with a test's temp $__fish_config_dir). Returning
    # here — before any write — keeps a rogue event from corrupting the live fragment.
    test -f $cat; or return
    set -l tmuxdir "$HOME/.config/tmux"
    set -l fragment "$tmuxdir/tmux-lives.conf"
    mkdir -p $tmuxdir
    __tmux_lives_render_fragment $cat (__tmux_lives_key tmux_lives_prefix_key S) (__tmux_lives_key tmux_lives_switcher_key M-s) (__tmux_lives_key tmux_lives_bar_color '') (__tmux_lives_key tmux_lives_status_invert 0) (__tmux_lives_key tmux_lives_modal_key M-m) (__tmux_lives_key tmux_lives_scratch_key M-t) (__tmux_lives_key tmux_lives_resize_key M-r) (__tmux_lives_key tmux_lives_status_pos_key C-M-a) (__tmux_lives_key tmux_lives_status_vis_key C-M-s) (__tmux_lives_key tmux_lives_cursor_style block) (__tmux_lives_key tmux_lives_theme_key M-k) (__tmux_lives_key tmux_lives_theme mono) (__tmux_lives_key tmux_lives_theme_place bar) (__tmux_lives_key tmux_lives_theme_mode derived) (__tmux_lives_key tmux_lives_theme_phase 0) (__tmux_lives_key tmux_lives_sync_terminals 'xterm*') > $fragment
    __tmux_lives_ensure_source_line "$HOME/.tmux.conf" $fragment
    __tmux_lives_reload
end

function __tmux_lives_setup --description 'tmux-lives: install fragment + tmux.conf wiring + TPM plugins + systemd units'
    set -l tmuxdir "$HOME/.config/tmux"
    set -l fragment "$tmuxdir/tmux-lives.conf"

    set -l tpm "$HOME/.tmux/plugins/tpm"
    test -d $tpm; or git clone -q https://github.com/tmux-plugins/tpm $tpm
    for p in tmux-resurrect tmux-continuum
        set -l d "$HOME/.tmux/plugins/$p"
        test -d $d; or git clone -q https://github.com/tmux-plugins/$p $d
    end
    echo "tmux-lives setup: TPM + resurrect + continuum present"

    __tmux_lives_write_fragment
    echo "tmux-lives setup: wrote $fragment"
    echo "tmux-lives setup: ensured source-file line in ~/.tmux.conf"

    __tmux_lives_seed_baseline (__tmux_lives_baseline_path)
    echo "tmux-lives setup: baseline file at "(__tmux_lives_baseline_path)" (edit: tmux-lives setup conf edit)"

    if type -q systemctl
        set -l user (id -un); set -l uid (id -u)
        echo "tmux-lives setup: installing systemd units (sudo required)…"
        __tmux_lives_save_unit_text $user $uid | sudo tee /etc/systemd/system/tmux-resurrect-save.service >/dev/null
        __tmux_lives_restore_unit_text $user $uid | sudo tee /etc/systemd/system/tmux-resurrect-restore.service >/dev/null
        sudo systemctl daemon-reload
        sudo systemctl enable --now tmux-resurrect-save.service
        sudo systemctl enable tmux-resurrect-restore.service
        echo "tmux-lives setup: systemd units installed + enabled"
    else
        echo "tmux-lives setup: "(__tmux_lives_persistence_note)
    end
    set -l had_server 0
    tmux list-sessions >/dev/null 2>&1; and set had_server 1
    if test $had_server -eq 1
        echo "tmux-lives setup: done — reloaded the running tmux; the switcher + persistence are live now."
    else
        echo "tmux-lives setup: done — start tmux to load the fragment."
    end
    echo "tmux-lives setup: run 'tmux-lives setup verify' anytime to check the install."
end

function __tmux_lives_remove_source_line --description 'Remove the fragment source-file line'
    set -l tmux_conf $argv[1]; set -l fragment $argv[2]
    test -f $tmux_conf; or return 0
    set -l tmp (mktemp)
    grep -vF -- "source-file $fragment" $tmux_conf > $tmp
    mv $tmp $tmux_conf
end

function __tmux_lives_teardown --description 'tmux-lives: remove fragment + tmux.conf wiring + systemd units'
    set -l fragment "$HOME/.config/tmux/tmux-lives.conf"
    __tmux_lives_remove_source_line "$HOME/.tmux.conf" $fragment
    rm -f $fragment
    echo "tmux-lives teardown: removed fragment + source-file line"
    if type -q systemctl
        echo "tmux-lives teardown: removing systemd units (sudo)…"
        sudo systemctl disable --now tmux-resurrect-save.service 2>/dev/null
        sudo systemctl disable tmux-resurrect-restore.service 2>/dev/null
        sudo rm -f /etc/systemd/system/tmux-resurrect-{save,restore}.service
        sudo systemctl daemon-reload
        echo "tmux-lives teardown: systemd units removed"
    end
    echo "tmux-lives teardown: done. (TPM plugins under ~/.tmux/plugins left in place.)"
end

function __tmux_lives_status_lines --description 'One status line per tmux-lives layer'
    set -l cat "$__fish_config_dir/functions/tmux-categorize.fish"
    set -l fragment "$HOME/.config/tmux/tmux-lives.conf"
    set -l r
    test -f "$__fish_config_dir/conf.d/tmux.fish"; and set -a r "OK conf.d/tmux.fish deployed"; or set -a r "MISSING conf.d/tmux.fish (fisher install …)"
    test -f $cat; and set -a r "OK categorizer deployed"; or set -a r "MISSING categorizer"
    test -f $fragment; and set -a r "OK tmux fragment present"; or set -a r "MISSING tmux fragment (run tmux-lives setup)"
    grep -qF -- "source-file $fragment" "$HOME/.tmux.conf" 2>/dev/null; and set -a r "OK ~/.tmux.conf sources fragment"; or set -a r "MISSING source-file line"
    test -d "$HOME/.tmux/plugins/tmux-resurrect"; and set -a r "OK tmux-resurrect present"; or set -a r "MISSING tmux-resurrect"
    if type -q systemctl
        systemctl is-enabled tmux-resurrect-save.service >/dev/null 2>&1; and set -a r "OK save service enabled"; or set -a r "MISSING save service (run tmux-lives setup)"
    else
        set -a r (__tmux_lives_persistence_status)
    end
    set -l pk (__tmux_lives_key tmux_lives_prefix_key S); test -n "$pk"; or set pk '(off)'
    set -l sk (__tmux_lives_key tmux_lives_switcher_key M-s); test -n "$sk"; or set sk '(off)'
    set -a r "OK switcher keys: prefix=$pk  no-prefix=$sk"
    set -l bc (__tmux_lives_key tmux_lives_bar_color ''); test -n "$bc"; or set bc '(none)'
    if test "$bc" = '(none)'
        set -a r "OK bar color: $bc"
    else
        set -l bdir lighter; test (__tmux_lives_key tmux_lives_status_invert 0) = 1; and set bdir darker
        set -a r "OK bar color: $bc (status bar: $bdir)"
    end
    set -l bf (__tmux_lives_baseline_path)
    test -e $bf; and set -a r "OK baseline $bf present"; or set -a r "OK baseline $bf (none yet)"
    printf '%s\n' $r
end

function __tmux_lives_help_hint --description 'Pointer to the tmux-lives help command'
    echo 'Run `tmux-lives` to see all commands.'
end

function __tmux_lives_box --argument-names title --description 'frame stdin lines in a rounded, orange-bordered box titled <title>'
    set -l ORG (printf '\e[38;5;208m')
    set -l RST (printf '\e[0m')
    set -l lines
    while read -l l
        set -a lines "$l"
    end
    # content-field width = widest line, measured in DISPLAY columns; at least wide
    # enough for the title that sits in the top edge
    set -l cw 0
    for l in $lines
        set -l w (string length --visible -- "$l")
        test $w -gt $cw; and set cw $w
    end
    set -l tw (string length --visible -- "$title")
    set -l tmin (math "$tw + 2")
    test $tmin -gt $cw; and set cw $tmin
    # top edge:  ╭─ <title> ─…─╮   (frame orange, title in the default fg)
    printf '%s╭─ %s%s%s %s╮%s\n' $ORG $RST "$title" $ORG (string repeat -n (math "$cw - $tw - 1") ─) $RST
    # content rows:  │ <line padded to cw> │
    # NB: pad goes through a quoted var — an inline (string repeat -n 0 …) yields ZERO
    # args (not one empty string), which would shift the trailing printf args.
    for l in $lines
        set -l pad (string repeat -n (math "$cw - "(string length --visible -- "$l")) ' ')
        printf '%s│%s %s%s %s│%s\n' $ORG $RST "$l" "$pad" $ORG $RST
    end
    # bottom edge:  ╰─…─╯
    printf '%s╰%s╯%s\n' $ORG (string repeat -n (math "$cw + 2") ─) $RST
end

function __tmux_lives_help_lines --description 'tmux-lives help content (unframed; alias-first columns)'
    printf '%s\n' \
        'categorized tmux sessions, switcher & persistence' \
        '' \
        'USAGE' \
        '  tmux-lives <command> [options]' \
        ''
    # alias-first rows — printf field widths align the columns (alias 2, command+args 28).
    # close keeps its `q` alias in the dispatcher but the help shows only `x`.
    printf '%-2s%-28s%s\n' '' 'setup <command> [options]' 'run `tmux-lives setup -h` for details'
    printf '%-2s%-28s%s\n' '' '' 'install · verify · teardown · keys · auto'
    printf '%-2s%-28s%s\n' u 'update' 'update the plugin (fisher update)'
    echo ''
    printf '%-2s%-28s%s\n' n 'new [name]' 'create a new session (optional name)'
    printf '%-2s%-28s%s\n' a 'attach <name> [-t]' 'attach to a session (-t takes it)'
    printf '%-2s%-28s%s\n' p 'picker [-t]' 'open the session switcher (-t takes it)'
    printf '%-2s%-28s%s\n' f 'fix' 'repair the SSH agent socket'
    printf '%-2s%-28s%s\n' c 'categorize' 're-categorize sessions (fix a bad name)'
    printf '%-2s%-28s%s\n' '' 'clear [-q|-x]' 'kill idle sessions (-q/-x also exits)'
    printf '%-2s%-28s%s\n' x 'close' 'kill the current session and exit'
end

function __tmux_lives_help --description 'tmux-lives command list'
    __tmux_lives_help_lines | __tmux_lives_box 'tmux-lives'
end

function __tmux_lives_keys_cmd --description 'tmux-lives setup keys [-p K] [-s K]'
    if test (count $argv) -eq 0
        echo "switcher keys: prefix="(__tmux_lives_key tmux_lives_prefix_key S)"  no-prefix="(__tmux_lives_key tmux_lives_switcher_key M-s)
        return 0
    end
    set -l changed 0
    while test (count $argv) -ge 2
        switch $argv[1]
            case -p --prefix-key
                set -U tmux_lives_prefix_key $argv[2]; set changed 1; set -e argv[1..2]
            case -s --switcher-key
                set -U tmux_lives_switcher_key $argv[2]; set changed 1; set -e argv[1..2]
            case --modal-key
                set -U tmux_lives_modal_key $argv[2]; set changed 1; set -e argv[1..2]
            case --scratch-key
                set -U tmux_lives_scratch_key $argv[2]; set changed 1; set -e argv[1..2]
            case --resize-key
                set -U tmux_lives_resize_key $argv[2]; set changed 1; set -e argv[1..2]
            case --status-pos-key
                set -U tmux_lives_status_pos_key $argv[2]; set changed 1; set -e argv[1..2]
            case --status-vis-key
                set -U tmux_lives_status_vis_key $argv[2]; set changed 1; set -e argv[1..2]
            case --theme-key
                set -U tmux_lives_theme_key $argv[2]; set changed 1; set -e argv[1..2]
            case '*'
                echo "tmux-lives setup keys: unknown option '$argv[1]'" >&2; return 1
        end
    end
    if test (count $argv) -gt 0
        echo "tmux-lives setup keys: incomplete option '$argv[1]'" >&2; return 1
    end
    test $changed -eq 1; and __tmux_lives_write_fragment
end

function __tmux_lives_seed_hex --argument-names css --description 'css color (#rrggbb / #rgb / rgb()) -> #rrggbb, lowercased; anything else (named colors, color(p3 ...)) -> nothing'
    set -l color (string lower -- "$css")
    test -n "$color"; or return
    set -l m (string match -rg '^#([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$' -- $color)
    if test (count $m) -eq 3
        echo $color
        return
    end
    set m (string match -rg '^#([0-9a-f])([0-9a-f])([0-9a-f])$' -- $color)
    if test (count $m) -eq 3
        echo "#$m[1]$m[1]$m[2]$m[2]$m[3]$m[3]"
        return
    end
    set m (string match -rg '^rgba?\(\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)' -- $color)
    if test (count $m) -eq 3
        set -l r $m[1]; set -l g $m[2]; set -l b $m[3]
        for v in r g b
            set -l x $$v
            test "$x" -gt 255; and set $v 255
        end
        printf '#%02x%02x%02x\n' $r $g $b
    end
end

function __tmux_lives_derive_status --description 'css color + invert(0/1) -> "bg=#rrggbb,fg=#rrggbb" for status-style; empty if unparseable'
    set -l invert $argv[2]
    set -l hexin (__tmux_lives_seed_hex $argv[1])
    test -n "$hexin"; or return
    set -l m (string match -rg '^#([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$' -- $hexin)
    set -l r (math "0x$m[1]"); set -l g (math "0x$m[2]"); set -l b (math "0x$m[3]")
    if test "$invert" = 1
        set r (math "round($r * 0.75)"); set g (math "round($g * 0.75)"); set b (math "round($b * 0.75)")
    else
        set r (math "round($r + (255 - $r) * 0.25)"); set g (math "round($g + (255 - $g) * 0.25)"); set b (math "round($b + (255 - $b) * 0.25)")
    end
    set -l hex (printf '#%02x%02x%02x' $r $g $b)
    # Tinted text (Light tint f=0.68): a hex shade of the bar's own hue, blended toward
    # white (dark bar) or black (light bar). Palette-independent; visible hue, still clearly
    # light/dark. fish `math` has no comparison operators -> integer luminance + test.
    set -l L (math "round(0.299 * $r + 0.587 * $g + 0.114 * $b)")
    set -l tr; set -l tg; set -l tb
    if test $L -gt 140
        set tr (math "round($r * 0.32)"); set tg (math "round($g * 0.32)"); set tb (math "round($b * 0.32)")
    else
        set tr (math "round($r + (255 - $r) * 0.68)"); set tg (math "round($g + (255 - $g) * 0.68)"); set tb (math "round($b + (255 - $b) * 0.68)")
    end
    echo "bg=$hex,fg="(printf '#%02x%02x%02x' $tr $tg $tb)
end

function __tmux_lives_derive_status_bg --description 'css color + invert -> just the bg hex of the derived status-style (empty if unparseable)'
    set -l ss (__tmux_lives_derive_status $argv[1] $argv[2])
    test -n "$ss"; or return 0
    string replace -rf '.*bg=([^,]+).*' '$1' -- $ss
end

# --- OKLCH conversion core (perceptual color space; feeds the v2 palette engine) ---
# sRGB <-> linear-light helpers (IEC 61966-2-1).
function __tmux_lives_lin_decode --argument c --description 'sRGB channel [0,1] -> linear-light (IEC 61966-2-1 EOTF)'
    if test $c -le 0.04045; math "$c / 12.92"; else; math "(($c + 0.055) / 1.055) ^ 2.4"; end
end
function __tmux_lives_lin_encode --argument c --description 'linear-light channel [0,1] -> sRGB (IEC 61966-2-1 OETF); c already clipped to [0,1]'
    if test $c -le 0.0031308; math "$c * 12.92"; else; math "1.055 * ($c ^ (1 / 2.4)) - 0.055"; end
end
function __tmux_lives_clip01 --argument v --description 'clamp a number into [0,1]'
    if test $v -lt 0; echo 0; return; end
    if test $v -gt 1; echo 1; return; end
    echo $v
end
function __tmux_lives_hex_to_rgb01 --argument hex --description '#rrggbb -> r,g,b (0-1) one per line'
    set -l h (string replace -r '^#' '' $hex)
    printf "%s\n" (math "0x"(string sub -s 1 -l 2 $h)"/255") (math "0x"(string sub -s 3 -l 2 $h)"/255") (math "0x"(string sub -s 5 -l 2 $h)"/255")
end
function __tmux_lives_linrgb_to_hex --argument r g b --description 'linear-light r,g,b (unclamped) -> #rrggbb (gamma-encode + clip01 + round)'
    set -l re (__tmux_lives_clip01 (__tmux_lives_lin_encode (__tmux_lives_clip01 $r)))
    set -l ge (__tmux_lives_clip01 (__tmux_lives_lin_encode (__tmux_lives_clip01 $g)))
    set -l be (__tmux_lives_clip01 (__tmux_lives_lin_encode (__tmux_lives_clip01 $b)))
    printf "#%02x%02x%02x\n" (math "round($re*255)") (math "round($ge*255)") (math "round($be*255)")
end
function __tmux_lives_rgb_to_oklch --argument r g b --description 'sRGB (0-1) -> OKLCH: prints L, C, H(deg 0-360) one per line'
    set -l rl (__tmux_lives_lin_decode $r); set -l gl (__tmux_lives_lin_decode $g); set -l bl (__tmux_lives_lin_decode $b)
    set -l l (math "0.4122214708*$rl + 0.5363325363*$gl + 0.0514459929*$bl")
    set -l m (math "0.2119034982*$rl + 0.6806995451*$gl + 0.1073969566*$bl")
    set -l s (math "0.0883024619*$rl + 0.2817188376*$gl + 0.6299787005*$bl")
    set -l lp (math "$l ^ (1/3)"); set -l mp (math "$m ^ (1/3)"); set -l sp (math "$s ^ (1/3)")
    set -l L (math "0.2104542553*$lp + 0.7936177850*$mp - 0.0040720468*$sp")
    set -l a (math "1.9779984951*$lp - 2.4285922050*$mp + 0.4505937099*$sp")
    set -l b (math "0.0259040371*$lp + 0.7827717662*$mp - 0.8086757660*$sp")
    set -l C (math "sqrt($a^2 + $b^2)")
    set -l H (math "atan2($b, $a) * 180 / $__tmux_lives_pi")
    if test $H -lt 0; set H (math "$H + 360"); end
    printf "%s\n" $L $C $H
end
function __tmux_lives_oklch_to_linrgb --argument L C H --description 'OKLCH -> linear r,g,b (unclamped) one per line'
    set -l Hrad (math "$H * $__tmux_lives_pi / 180")
    set -l a (math "$C * cos($Hrad)"); set -l b (math "$C * sin($Hrad)")
    set -l lp (math "$L + 0.3963377774*$a + 0.2158037573*$b")
    set -l mp (math "$L - 0.1055613458*$a - 0.0638541728*$b")
    set -l sp (math "$L - 0.0894841775*$a - 1.2914855480*$b")
    set -l l (math "$lp ^ 3"); set -l m (math "$mp ^ 3"); set -l s (math "$sp ^ 3")
    printf "%s\n" (math "4.0767416621*$l - 3.3077115913*$m + 0.2309699292*$s") (math "-1.2684380046*$l + 2.6097574011*$m - 0.3413193965*$s") (math "-0.0041960863*$l - 0.7034186147*$m + 1.7076147010*$s")
end
function __tmux_lives_in_gamut --argument r g b --description 'linear r,g,b each in [0,1]? -> 1/0'
    for v in $r $g $b
        if test $v -lt 0; echo 0; return; end
        if test $v -gt 1; echo 0; return; end
    end
    echo 1
end
function __tmux_lives_gamut_chroma --argument L H Ctarget --description 'max in-gamut chroma <= Ctarget (12-iter bisection)'
    set -l rgb (__tmux_lives_oklch_to_linrgb $L $Ctarget $H)
    if test (__tmux_lives_in_gamut $rgb[1] $rgb[2] $rgb[3]) -eq 1; echo $Ctarget; return; end
    set -l lo 0; set -l hi $Ctarget
    for i in (seq 1 12)
        set -l mid (math "($lo + $hi) / 2")
        set -l rgb2 (__tmux_lives_oklch_to_linrgb $L $mid $H)
        if test (__tmux_lives_in_gamut $rgb2[1] $rgb2[2] $rgb2[3]) -eq 1; set lo $mid; else; set hi $mid; end
    end
    echo $lo
end
function __tmux_lives_oklch_hex --argument L C H --description 'OKLCH -> #rrggbb (chroma gamut-clamped, gamma-encoded, clipped)'
    set -l Cg (__tmux_lives_gamut_chroma $L $H $C)
    set -l rgb (__tmux_lives_oklch_to_linrgb $L $Cg $H)
    __tmux_lives_linrgb_to_hex $rgb[1] $rgb[2] $rgb[3]
end
function __tmux_lives_norm360 --argument h --description 'wrap a hue in degrees into [0,360)'
    set -l hh $h
    while test $hh -lt 0; set hh (math "$hh + 360"); end
    while test $hh -ge 360; set hh (math "$hh - 360"); end
    echo $hh
end
function __tmux_lives_theme_anchors --argument-names hue mode --description 'v6 harmony: a seed hue + a harmony mode -> 1-4 hue angles, wrapped into [0,360). Hues ONLY — no lightness, no chroma; those are the ramps job. The seeds own hue is always anchor one in every mode, so the seed anchors the palette rather than merely influencing it. This replaces the v5 signed-travel relationships, which walk an arc and therefore cannot produce SEPARATED hue families: triadic and square need hues to jump. Unknown mode -> nothing, status 1.'
    set -l offs
    switch "$mode"
        case mono
            set offs 0
        case analogous
            # 0 first, not -30: the seed must be anchor ONE in every mode.
            set offs 0 -30 30
        case complementary
            set offs 0 180
        case split
            set offs 0 150 210
        case triadic
            set offs 0 120 240
        case tetradic
            set offs 0 60 180 240
        case square
            set offs 0 90 180 270
        case '*'
            return 1
    end
    for o in $offs
        __tmux_lives_norm360 (math "$hue + $o")
    end
end

function __tmux_lives_theme_ramp --argument-names seedL Lspan peakC peakPos n --description 'v6 value structure: <n> (L, C) pairs, dark to light, one per line as "<L> <C>". Lightness spreads across a window of width <Lspan> positioned so the SEEDS OWN L falls inside it — that is how the seed stops being hue-only, which is the v5 defect this replaces (there, seed chroma and lightness were discarded entirely and every saturated seed converged on the same bar). Chroma peaks at <peakPos> (0 = darkest end, 1 = lightest) with maximum <peakC>, falling toward a floor away from the peak. The three are INDEPENDENT by design and by test: measured on 16 real palettes, peakC vs Lspan r = -0.29, so collapsing them into one "intensity" axis would be wrong.'
    test "$n" -lt 2; and return 1
    # Centre the window on the seed, then SHIFT (never shrink) to stay in gamut,
    # so a dark or light seed keeps the span the recipe asked for.
    set -l half (math "$Lspan / 2")
    set -l lo (math "$seedL - $half")
    set -l hi (math "$seedL + $half")
    if test "$lo" -lt 0.05
        set hi (math "$hi + (0.05 - $lo)")
        set lo 0.05
    end
    if test "$hi" -gt 0.97
        set lo (math "$lo - ($hi - 0.97)")
        set hi 0.97
    end
    test "$lo" -lt 0.05; and set lo 0.05
    set -l step (math "($hi - $lo) / ($n - 1)")
    # Chroma floor: away from the peak the ramp relaxes toward this rather than
    # to zero, so a muted recipe still reads as tinted rather than grey.
    set -l cfloor 0.012
    set -l far (math "max($peakPos, 1 - $peakPos)")
    test "$far" -lt 0.0001; and set far 1
    for i in (seq $n)
        set -l L (math "$lo + $step * ($i - 1)")
        set -l tpos (math "($i - 1) / ($n - 1)")
        set -l d (math "abs($tpos - $peakPos)")
        set -l frac (math "1 - ($d / $far)")
        test "$frac" -lt 0; and set frac 0
        set -l C (math "$cfloor + ($peakC - $cfloor) * $frac")
        test "$C" -lt 0; and set C 0
        printf '%s %s\n' $L $C
    end
end

function __tmux_lives_contrast_fg --argument-names hex --description 'bg hex -> readable fg via WCAG relative luminance: #111111 (light-ish bg) or #f5f5f5 (dark bg), crossover 0.179. Non-hex input (e.g. a tmux colourNNN fallback from a caller) -> #f5f5f5, matching v1s unparseable fallback.'
    set -l m (string match -rg '^#([0-9a-f]{6})$' -- (string lower -- $hex))
    test (count $m) -eq 1; or begin; echo '#f5f5f5'; return; end
    set -l rgb (__tmux_lives_hex_to_rgb01 $hex)
    set -l Lrel (math "0.2126*"(__tmux_lives_lin_decode $rgb[1])" + 0.7152*"(__tmux_lives_lin_decode $rgb[2])" + 0.0722*"(__tmux_lives_lin_decode $rgb[3]))
    if test $Lrel -gt 0.179; echo "#111111"; else; echo "#f5f5f5"; end
end

# --- theme engine v5: relationship-curve palette assembly ---------------------
# bar/tabs/cap come from __tmux_lives_theme_curve (relationship travel, seed
# placement, mode, the bridged endcap); sep/active/windows/text are lightness
# tints/contrast off the bar, built here.
function __tmux_lives_theme_accents --argument-names barHex capHex --description 'v5 accents: sep active windows text as lightness tints/contrast off the bar (uncalibrated, live-tunable via @options). -> sep active windows text (4 hexes).'
    string match -qr '^#[0-9a-fA-F]{6}$' -- "$barHex"; or return
    set -l brgb (__tmux_lives_hex_to_rgb01 $barHex)
    set -l bo (__tmux_lives_rgb_to_oklch $brgb[1] $brgb[2] $brgb[3])
    set -l bH $bo[3]
    # tints sit on the contrast side of the bar (light on a dark bar)
    set -l active  (__tmux_lives_oklch_hex 0.88 0.03 $bH)
    set -l windows (__tmux_lives_oklch_hex 0.74 0.04 $bH)
    set -l sep     (__tmux_lives_oklch_hex 0.62 0.03 $bH)
    if test $bo[1] -ge 0.55
        set active  (__tmux_lives_oklch_hex 0.16 0.03 $bH)
        set windows (__tmux_lives_oklch_hex 0.30 0.04 $bH)
        set sep     (__tmux_lives_oklch_hex 0.42 0.03 $bH)
    end
    set -l tdir 1
    test $bo[1] -ge 0.55; and set tdir -1
    set -l Lt (math "$bo[1] + $tdir * 0.45")
    test $Lt -lt 0.05; and set Lt 0.05
    test $Lt -gt 0.97; and set Lt 0.97
    set -l text (__tmux_lives_oklch_hex $Lt 0.03 $bH)
    printf '%s\n' $sep $active $windows $text
end

function __tmux_lives_theme_palette --argument-names seedHex relationship place mode phase --description 'v5: seed + relationship/place/mode/phase -> 7 role hexes (bar sep tabs active windows cap text). bar/tabs/cap = the curve (relationship travel, seed placement, mode, the bridged endcap); sep/active/windows/text = tints/contrast off the bar. Non-hex seed / unknown relationship -> nothing.'
    set -l tri (__tmux_lives_theme_curve "$seedHex" "$relationship" "$place" "$mode" "$phase")
    test (count $tri) -eq 3; or return
    set -l acc (__tmux_lives_theme_accents $tri[1] $tri[3])
    test (count $acc) -eq 4; or return
    # order: bar sep tabs active windows cap text
    printf '%s\n' $tri[1] $acc[1] $tri[2] $acc[2] $acc[3] $tri[3] $acc[4]
end

function __tmux_lives_color_cmd --description 'tmux-lives setup color [<css-color>] [-i|--invert] [-a|--apply]: ShellFish tab color + derived status bar; --apply reapplies the stored color live'
    set -l invert 0
    set -l color
    set -l have_color 0
    set -l apply 0
    for a in $argv
        switch $a
            case -i --invert
                set invert 1
            case -a --apply
                set apply 1
            case '*'
                set color $a; set have_color 1
        end
    end
    if test $apply -eq 1
        if test $have_color -eq 1
            echo "tmux-lives setup color: --apply takes no color argument" >&2
            return 1
        end
        set -l c (__tmux_lives_key tmux_lives_bar_color '')
        if test -z "$c"
            echo "tmux-lives: no seed set — set one with: tmux-lives setup color \"#rrggbb\"" >&2
            return 1
        end
        set -l _theme (__tmux_lives_key tmux_lives_theme mono)
        if test "$_theme" != off
            __tmux_lives_theme_apply_live
        else
            set -l ss (__tmux_lives_derive_status $c (__tmux_lives_key tmux_lives_status_invert 0))
            if test -n "$ss"
                if set -q tmux_lives_tmux_socket
                    command tmux -L $tmux_lives_tmux_socket set -g status-style $ss 2>/dev/null
                else
                    tmux set -g status-style $ss 2>/dev/null
                end
            end
        end
        set -l cat "$__fish_config_dir/functions/tmux-categorize.fish"
        test -f $cat; and fish --no-config $cat recolor $c 2>/dev/null
        echo "tmux-lives: reapplied seed $c"
        return 0
    end
    if test (count $argv) -eq 0
        set -l c (__tmux_lives_key tmux_lives_bar_color '')
        set -l dir lighter; test (__tmux_lives_key tmux_lives_status_invert 0) = 1; and set dir darker
        test -n "$c"; and echo "seed: $c (status bar: $dir)"; or echo "seed: (none)"
        return 0
    end
    if test $have_color -eq 0
        echo "tmux-lives setup color: -i needs a color, e.g. tmux-lives setup color \"#1f6feb\" -i" >&2
        return 1
    end
    if test -n "$color"; and string match -qr '[^A-Za-z0-9#(),./% -]' -- $color
        echo "tmux-lives setup color: invalid color '$color' — use a CSS color (red, #1f6feb, rgb(...), color(p3 ...))" >&2
        return 1
    end
    # Normalize a bare 3/6-digit hex to #rrggbb so __tmux_lives_derive_status (which
    # requires the leading #) can parse it; named colours / rgb()/color() are left alone.
    if string match -qr '^[0-9A-Fa-f]{3}$' -- $color; or string match -qr '^[0-9A-Fa-f]{6}$' -- $color
        set color "#$color"
    end
    set -U tmux_lives_bar_color $color
    set -U tmux_lives_status_invert $invert
    __tmux_lives_write_fragment
    # Re-emit the ShellFish OSC to attached clients now, so their tab colour updates
    # without waiting for the next client-attached. The emit logic lives in the categorizer.
    set -l cat "$__fish_config_dir/functions/tmux-categorize.fish"
    test -f $cat; and fish --no-config $cat recolor $color 2>/dev/null
    if test -n "$color"
        set -l dir lighter; test $invert -eq 1; and set dir darker
        echo "tmux-lives: seed set to $color (drives the theme + ShellFish tabs; status bar $dir)"
    else
        echo "tmux-lives: seed cleared"
    end
end

# --- theme engine v3: user surface -------------------------------------------
function __tmux_lives_theme_relationships --description 'v5 relationship names (signed hue travels), one per line — the ONE home of the list (CLI validation, list, picker all consume it)'
    printf '%s\n' mono wheat amber ember coral mint sage teal
end

function __tmux_lives_theme_catalog --description 'v5 gallery catalog: 35 schemes as name|relationship|place|mode|default (1 = in the curated default 14). Tiers glow/chip/core/soft/slate/deep — LITERAL rows first (bar, then tabs, then cap), then DERIVED rows (bar, then tabs, then cap): 18 literal followed by 17 derived, so the two groups sit contiguous and comparable, per the user request to see seed-literal and seed-figurative schemes as trends rather than interleaved. bar and tabs are SYMMETRIC (all 8 relationships x both modes) except mono, which has no tabs|derived row — mono still appears at tabs via mono|tabs|literal (chip); mono|tabs|derived is omitted because at zero travel, anchoring the bar and anchoring the tabs are the same operation, so that row could only duplicate mono|bar|derived. cap survives as a 4-row accent-led minority, split across the two groups (core in the literal half, deep in the derived half) — there neither large area is anchored, which is the inversion the big-area model exists to remove. Rows within a tier run safe -> wild by |travel|. Shared source of truth for the picker + setup theme list.'
    printf '%s\n' \
        'mono glow|mono|bar|literal|0'    'wheat glow|wheat|bar|literal|0' \
        'mint glow|mint|bar|literal|0'    'amber glow|amber|bar|literal|0' \
        'sage glow|sage|bar|literal|1'    'ember glow|ember|bar|literal|0' \
        'teal glow|teal|bar|literal|1'    'coral glow|coral|bar|literal|0' \
        'mono chip|mono|tabs|literal|0'   'wheat chip|wheat|tabs|literal|0' \
        'mint chip|mint|tabs|literal|1'   'amber chip|amber|tabs|literal|0' \
        'sage chip|sage|tabs|literal|1'   'ember chip|ember|tabs|literal|0' \
        'teal chip|teal|tabs|literal|0'   'coral chip|coral|tabs|literal|1' \
        'sage core|sage|cap|literal|1'    'teal core|teal|cap|literal|0' \
        'mono soft|mono|bar|derived|1'    'wheat soft|wheat|bar|derived|1' \
        'mint soft|mint|bar|derived|0'    'amber soft|amber|bar|derived|1' \
        'sage soft|sage|bar|derived|0'    'ember soft|ember|bar|derived|0' \
        'teal soft|teal|bar|derived|0'    'coral soft|coral|bar|derived|0' \
        'wheat slate|wheat|tabs|derived|1' 'mint slate|mint|tabs|derived|0' \
        'amber slate|amber|tabs|derived|1' 'sage slate|sage|tabs|derived|0' \
        'ember slate|ember|tabs|derived|1' 'teal slate|teal|tabs|derived|1' \
        'coral slate|coral|tabs|derived|0' \
        'amber deep|amber|cap|derived|1'  'coral deep|coral|cap|derived|0'
end

function __tmux_lives_theme_catalog_default --description 'the curated default set (14): catalog rows flagged default=1'
    # -e/--entire: plain `-r '\|1$'` outputs only the matched substring ("|1"),
    # not the whole line, since the pattern isn't anchored at the start — a real
    # fish landmine (verified empirically). --entire emits the full matching line.
    __tmux_lives_theme_catalog | string match -re '\|1$'
end

function __tmux_lives_theme_catalog_rest --description 'the non-curated catalog rows (21): everything NOT flagged default=1, in catalog order. The picker appends these under the More Schemes header when expanded, so the curated 14 keep their positions instead of being reshuffled into tier order.'
    # -v inverts; --entire is not needed with -v (it emits whole non-matching lines).
    __tmux_lives_theme_catalog | string match -rv '\|1$'
end

function __tmux_lives_theme_reldef --argument-names name --description 'v5 relationship -> signed hue travel in degrees (warm negative, cool positive); unknown -> nothing'
    switch "$name"
        case mono;  echo 0
        case wheat; echo -20
        case amber; echo -40
        case ember; echo -72
        case coral; echo -100
        case mint;  echo 20
        case sage;  echo 40
        case teal;  echo 72
    end
end

function __tmux_lives_theme_family --argument-names hue --description 'v5 kin-cap family table: an OKLCH hue -> the minimum hue separation, in degrees, that the endcap keeps from the bar. Usually called at the BAR hue (place=bar|tabs); at place=cap the bar is what is being solved for, so the call site passes the SEED hue instead — a deliberate single-pass approximation, not an iteration (see the call site comment). Fitted in the 2026-07-20 calibration study (4 rounds, blind numbered tiles; ~84% of judgments explained, and the rule-generated validation batch scored 9/10 vs 5/10 pre-rule). Restored from the v3.3 kincap rule the v4 rewrite deleted, in the role it was actually fitted for: bar and endcap judged as a PAIR. Blue and red/pink are untested extrapolations — first suspects if a future seed misbehaves.'
    set -l h (__tmux_lives_norm360 $hue)
    if test $h -ge 40; and test $h -lt 90
        echo 40
    else if test $h -ge 90; and test $h -lt 160
        echo 20
    else if test $h -ge 160; and test $h -lt 210
        echo 30
    else if test $h -ge 210; and test $h -lt 280
        echo 25
    else if test $h -ge 280; and test $h -lt 330
        echo 18
    else
        echo 15
    end
end

function __tmux_lives_theme_curve --argument-names seedHex relationship place mode phase --description 'v5 core: TWO LARGE AREAS AND A BRIDGE. The seed anchors one large area (place = bar|tabs anchors a LARGE area; place = cap anchors the endcap instead (the accent-led minority) and solves the bar backwards); the relationship signed travel separates the OTHER large area from it; the endcap bridges at half that travel, floored at the calibrated family separation so it never collapses into the bar. Depth is FIXED per role — hue differentiates, lightness coheres. Derived: seed L/C damped into the ramp; literal: the placed role renders the seed verbatim. -> bar tabs cap (3 hexes). Non-hex seed / unknown relationship -> nothing.'
    string match -qr '^#[0-9a-fA-F]{6}$' -- "$seedHex"; or return
    set -l sd (__tmux_lives_theme_reldef "$relationship")
    test -n "$sd"; or return
    test -n "$phase"; or set phase 0
    set -l rgb (__tmux_lives_hex_to_rgb01 $seedHex)
    set -l ok (__tmux_lives_rgb_to_oklch $rgb[1] $rgb[2] $rgb[3])
    set -l sL $ok[1]; set -l sC $ok[2]; set -l sH $ok[3]
    # damped seed influence on the derived ramp
    # (fish `test` compares floats with -lt/-gt; `math` has NO comparison ops)
    set -l Ldamp (math "0.5 * ($sL - 0.51)")
    test $Ldamp -lt -0.10; and set Ldamp -0.10
    test $Ldamp -gt 0.10; and set Ldamp 0.10
    set -l Cscale (math "0.5 * ($sC / 0.078 - 1) + 1")
    test $Cscale -lt 0.6; and set Cscale 0.6
    test $Cscale -gt 1.4; and set Cscale 1.4
    # depth is FIXED per role: the bar is the dark ground, the tab bar one step lighter.
    # 0.0713 is exactly what the deleted taper produced at zero travel (0.115 * 0.62),
    # so mono's two large areas are byte-identical to the pre-rewrite engine.
    set -l Lbar (math "0.40 + $Ldamp")
    set -l Ltabs (math "0.51 + $Ldamp")
    set -l Cbar (math "0.045 * $Cscale")
    set -l Ctabs (math "0.0713 * $Cscale")
    # signed bridge offset, measured FROM THE BAR: half the tab bar's travel. At
    # place=tabs the bar is the one that travelled, so the tabs sit at -sd from it and
    # the cap comes back toward them. Direction is the travel's, + when travel is zero.
    set -l half (math "$sd / 2")
    test "$place" = tabs; and set half (math "0 - $sd / 2")
    set -l dir 1
    test $half -lt 0; and set dir -1
    # the seed anchors one large area; the OTHER travels by sd.
    set -l capseed 0
    set -l Hbar $sH
    set -l Htabs $sH
    switch "$place"
        case tabs
            set Hbar (math "$sH + $sd")
        case cap
            # the seed lands on the ENDCAP; solve the bar backwards. The bridge offset
            # depends on the BAR's hue, which is what we are solving for, so the family
            # separation is evaluated at the SEED's hue — a deliberate single pass, not
            # an iteration. Deterministic and testable.
            set capseed 1
            set -l m0 (math "abs($sd / 2)")
            set -l f0 (__tmux_lives_theme_family $sH)
            test $m0 -lt $f0; and set m0 $f0
            set Hbar (math "$sH - $dir * $m0")
            set Htabs (math "$Hbar + $sd")
        case '*'
            set Htabs (math "$sH + $sd")
    end
    set Hbar (__tmux_lives_norm360 (math "$Hbar + $phase"))
    set Htabs (__tmux_lives_norm360 (math "$Htabs + $phase"))
    # clamp the L values (unrolled — avoids the $$var-indirection gotcha)
    test $Lbar -lt 0.05; and set Lbar 0.05
    test $Lbar -gt 0.95; and set Lbar 0.95
    test $Ltabs -lt 0.05; and set Ltabs 0.05
    test $Ltabs -gt 0.95; and set Ltabs 0.95
    set -l bar (__tmux_lives_oklch_hex $Lbar $Cbar $Hbar)
    set -l tabs (__tmux_lives_oklch_hex $Ltabs $Ctabs $Htabs)
    # literal: the placed role renders the seed's EXACT hex (verbatim, not a recompute —
    # an OKLCH round-trip can drift a channel). The anchor already lands that role's
    # derived hue on the seed hue; this pins its L and C to the seed too.
    if test "$mode" = literal
        set -l s (string lower -- $seedHex)
        switch "$place"
            case tabs; set tabs $s
            case cap;  # the cap is the seed — pinned below, where the cap is built
            case '*';  set bar $s
        end
    end
    # endcap = quiet BRIDGE off the RENDERED bar (so `literal` is honoured): half the
    # travel, floored at the calibrated family separation.
    set -l brgb (__tmux_lives_hex_to_rgb01 $bar)
    set -l bok (__tmux_lives_rgb_to_oklch $brgb[1] $brgb[2] $brgb[3])
    set -l Lcap (math "$bok[1] + 0.10")
    test $bok[1] -ge 0.55; and set Lcap (math "$bok[1] - 0.10")
    test $Lcap -lt 0.05; and set Lcap 0.05
    test $Lcap -gt 0.95; and set Lcap 0.95
    set -l cap
    if test $capseed -eq 1
        # the seed is placed HERE: verbatim in literal, at cap depth on the seed's hue
        # in derived. Either way the cap is the anchor and does not move by relationship.
        if test "$mode" = literal
            set cap (string lower -- $seedHex)
        else
            set cap (__tmux_lives_oklch_hex $Lcap $bok[2] (__tmux_lives_norm360 (math "$sH + $phase")))
        end
    else
        set -l mag (math "abs($half)")
        set -l minsep (__tmux_lives_theme_family $bok[3])
        test $mag -lt $minsep; and set mag $minsep
        set -l Hcap (__tmux_lives_norm360 (math "$bok[3] + $dir * $mag"))
        set cap (__tmux_lives_oklch_hex $Lcap $bok[2] $Hcap)
    end
    printf '%s\n' $bar $tabs $cap
end

function __tmux_lives_theme_valid --argument-names token --description 'true if token is a v5 relationship name'
    contains -- "$token" (__tmux_lives_theme_relationships)
end

function __tmux_lives_theme_push --description 'internal: tmux set -g <option> <value> honoring the tmux_lives_tmux_socket test seam'
    if set -q tmux_lives_tmux_socket
        command tmux -L $tmux_lives_tmux_socket set -g $argv 2>/dev/null
    else
        tmux set -g $argv 2>/dev/null
    end
end

function __tmux_lives_theme_apply_live --description 'internal: push the effective v5 theme (or legacy when off/seedless) to the live server. With exactly 4 args (relationship place mode phase) pushes THOSE values instead of the universals — the picker preview path; writes no state.'
    set -l theme; set -l place; set -l mode; set -l phase
    if test (count $argv) -eq 4
        set theme $argv[1]; set place $argv[2]; set mode $argv[3]; set phase $argv[4]
    else
        set theme (__tmux_lives_key tmux_lives_theme mono)
        set place (__tmux_lives_key tmux_lives_theme_place bar)
        set mode (__tmux_lives_key tmux_lives_theme_mode derived)
        set phase (__tmux_lives_key tmux_lives_theme_phase 0)
    end
    set -l seed (__tmux_lives_seed_hex (__tmux_lives_key tmux_lives_bar_color ''))
    set -l tpal
    if test "$theme" != off; and test -n "$seed"
        set tpal (__tmux_lives_theme_palette $seed "$theme" "$place" "$mode" $phase)
    end
    if test (count $tpal) -eq 7
        __tmux_lives_theme_push status-style "bg=$tpal[1],fg=$tpal[5]"
        __tmux_lives_theme_push @tmux_lives_bar_bg $tpal[1]
        __tmux_lives_theme_push @tmux_lives_sep_fg $tpal[2]
        __tmux_lives_theme_push @tmux_lives_tabs_color $tpal[3]
        __tmux_lives_theme_push @tmux_lives_active_fg $tpal[4]
        __tmux_lives_theme_push @tmux_lives_cap_bg $tpal[6]
        __tmux_lives_theme_push @tmux_lives_cap_fg (__tmux_lives_contrast_fg $tpal[6])
        __tmux_lives_theme_push @tmux_lives_mark_fg $seed
        __tmux_lives_theme_push @tmux_lives_text_fg $tpal[7]
        return 0
    end
    # legacy (theme off, or no usable seed): derived bar + neutral cap + no-op role seeds
    set -l ss (__tmux_lives_derive_status (__tmux_lives_key tmux_lives_bar_color '') (__tmux_lives_key tmux_lives_status_invert 0))
    test -n "$ss"; and __tmux_lives_theme_push status-style $ss
    set -l barbg (__tmux_lives_derive_status_bg (__tmux_lives_key tmux_lives_bar_color '') (__tmux_lives_key tmux_lives_status_invert 0))
    test -n "$barbg"; or set barbg colour236
    __tmux_lives_theme_push @tmux_lives_bar_bg $barbg
    __tmux_lives_theme_push @tmux_lives_cap_bg colour238
    __tmux_lives_theme_push @tmux_lives_cap_fg (__tmux_lives_contrast_fg colour238)
    __tmux_lives_theme_push @tmux_lives_sep_fg default
    __tmux_lives_theme_push @tmux_lives_tabs_color ''
    __tmux_lives_theme_push @tmux_lives_active_fg default
    __tmux_lives_theme_push @tmux_lives_mark_fg default
    __tmux_lives_theme_push @tmux_lives_text_fg default
end

function __tmux_lives_theme_list --description 'tmux-lives setup theme list: every catalog scheme + a 7-role gradient strip at the current seed/phase'
    set -l seed (__tmux_lives_seed_hex (__tmux_lives_key tmux_lives_bar_color ''))
    test -n "$seed"; or set seed '#3a3a3a'   # no seed configured yet -> neutral so strips still render
    set -l phase (__tmux_lives_key tmux_lives_theme_phase 0)
    for entry in (__tmux_lives_theme_catalog)
        set -l f (string split '|' $entry)
        set -l name $f[1]
        set -l rel $f[2]
        set -l place $f[3]
        set -l mode $f[4]
        set -l pal (__tmux_lives_theme_palette $seed $rel $place $mode $phase)
        test (count $pal) -eq 7; or continue
        set -l strip
        for hex in $pal
            set -l m (string match -rg '^#([0-9a-fA-F]{2})([0-9a-fA-F]{2})([0-9a-fA-F]{2})$' -- $hex)
            test (count $m) -eq 3; or continue
            set -a strip (printf '\e[48;2;%d;%d;%dm  \e[0m' (math "0x$m[1]") (math "0x$m[2]") (math "0x$m[3]"))
        end
        printf '%s %-11s %s\n' (string join '' $strip) $name $pal[6]
    end
end

function __tmux_lives_theme_cmd --description 'tmux-lives setup theme [<relationship>|list|off] [--phase <deg>] [--place bar|tabs|cap] [--mode literal|derived]: the v5 bar theme (relationship x placement x mode)'
    if test (count $argv) -eq 0
        # inside tmux with display-popup: open the picker (the discovery surface);
        # otherwise print the current state.
        if set -q TMUX; and tmux list-commands 2>/dev/null | grep -q display-popup
            set -l cat "$__fish_config_dir/functions/tmux-categorize.fish"
            if test -f $cat
                set -l client (tmux display-message -p '#{client_name}' 2>/dev/null)
                tmux display-popup -B -E -w 52 -h 85% -- fish --no-config $cat theme-picker "$client"
                return 0
            end
        end
        set -l cur (__tmux_lives_key tmux_lives_theme mono)
        test "$cur" = off; and echo "theme: off (legacy bar colors)"; or echo "theme: $cur"
        set -l tphase (__tmux_lives_key tmux_lives_theme_phase 0)
        set -l tplace (__tmux_lives_key tmux_lives_theme_place bar)
        set -l tmode (__tmux_lives_key tmux_lives_theme_mode derived)
        echo "  phase: $tphase   place: $tplace   mode: $tmode"
        return 0
    end
    set -l scheme; set -l have_scheme 0
    set -l phase; set -l have_phase 0
    set -l place; set -l have_place 0
    set -l mode; set -l have_mode 0
    set -l i 1
    while test $i -le (count $argv)
        switch $argv[$i]
            case list
                __tmux_lives_theme_list
                return
            case off
                set -U tmux_lives_theme off
                __tmux_lives_write_fragment
                __tmux_lives_theme_apply_live
                echo "tmux-lives: theme off — legacy bar colors (re-enable with 'tmux-lives setup theme mono')"
                return 0
            case --phase
                set i (math $i + 1); set phase $argv[$i]; set have_phase 1
            case --vividness --shape --ease --contrast
                echo "tmux-lives setup theme: $argv[$i] was removed in v5.1 — it never affected the output" >&2
                return 1
            case --place
                set i (math $i + 1); set place $argv[$i]; set have_place 1
            case --mode
                set i (math $i + 1); set mode $argv[$i]; set have_mode 1
            case --rotate
                echo "tmux-lives setup theme: --rotate was removed in v4 — use --place bar|tabs|cap to move the seed instead" >&2
                return 1
            case '*'
                set scheme $argv[$i]; set have_scheme 1
        end
        set i (math $i + 1)
    end
    # Validate everything before mutating any state (same contract as setup cap).
    if test $have_scheme -eq 1; and not __tmux_lives_theme_valid "$scheme"
        echo "tmux-lives setup theme: invalid relationship '$scheme' — valid: "(__tmux_lives_theme_relationships | string join ', ')" (or: list, off)" >&2
        return 1
    end
    if test $have_phase -eq 1; and not string match -qr -- '^-?[0-9]+$' "$phase"
        echo "tmux-lives setup theme: invalid phase '$phase' — whole degrees, e.g. --phase -30" >&2
        return 1
    end
    test $have_phase -eq 1; and set phase (math "$phase % 360")
    if test $have_place -eq 1
        switch "$place"
            case bar tabs cap
            case '*'
                echo "tmux-lives setup theme: invalid place '$place' — valid: bar, tabs, cap" >&2
                return 1
        end
    end
    if test $have_mode -eq 1
        switch "$mode"
            case literal derived
            case '*'
                echo "tmux-lives setup theme: invalid mode '$mode' — valid: literal, derived" >&2
                return 1
        end
    end
    if test $have_scheme -eq 1
        set -l seed (__tmux_lives_seed_hex (__tmux_lives_key tmux_lives_bar_color ''))
        if test -z "$seed"
            echo "tmux-lives setup theme: no seed color — set one first: tmux-lives setup color '#rrggbb' (hex or rgb(); named colors have no derivable hue)" >&2
            return 1
        end
    end
    test $have_phase -eq 1; and set -U tmux_lives_theme_phase $phase
    test $have_place -eq 1; and set -U tmux_lives_theme_place $place
    test $have_mode -eq 1; and set -U tmux_lives_theme_mode $mode
    test $have_scheme -eq 1; and set -U tmux_lives_theme $scheme
    # Persist into the fragment AND apply live (no reattach): write_fragment re-renders +
    # reloads; apply_live covers a server the reload can't reach (and the test seam).
    __tmux_lives_write_fragment
    __tmux_lives_theme_apply_live
    test $have_scheme -eq 1; and echo "tmux-lives: theme set to $scheme"
    test $have_phase -eq 1; and echo "tmux-lives: theme phase set to $phase"
    test $have_place -eq 1; and echo "tmux-lives: theme place set to $place"
    test $have_mode -eq 1; and echo "tmux-lives: theme mode set to $mode"
end

function __tmux_lives_baseline_path --description 'path to the user-owned non-ShellFish baseline file (seam: tmux_lives_baseline_conf)'
    # Default mirrors __tcz_on_attach's baseline path in functions/tmux-categorize.fish — keep in sync.
    set -q tmux_lives_baseline_conf; and echo $tmux_lives_baseline_conf; or echo "$HOME/.tmux-lives.conf"
end

function __tmux_lives_state_path --description 'path to the machine-owned status-toggle state file (seam: tmux_lives_state_file)'
    # Default mirrors __tcz_write_state's inline path in functions/tmux-categorize.fish — keep in sync.
    set -q tmux_lives_state_file; and echo $tmux_lives_state_file; or echo "$HOME/.config/tmux/tmux-lives-state.conf"
end

function __tmux_lives_funcs_path --description 'path to the record of shipped function names, used to spot removals across an update (seam: tmux_lives_funcs_file)'
    set -q tmux_lives_funcs_file; and echo $tmux_lives_funcs_file; or echo "$HOME/.config/tmux/tmux-lives-funcs"
end

function __tmux_lives_shipped_functions --argument-names dir --description 'names of the functions this plugin defines, read from its installed files. Defaults to $__fish_config_dir; takes a directory so tests can point it at the repo.'
    test -n "$dir"; or set dir $__fish_config_dir
    set -l names
    for f in $dir/conf.d/tmux.fish $dir/conf.d/tmux-lives-install.fish $dir/functions/tmux-categorize.fish
        test -f $f; or continue
        # `function NAME --flags…` — the name is the first word after `function`
        for line in (string match -r '^function\s+\S+' < $f)
            set -a names (string split -f2 ' ' -- (string replace -r '\s+' ' ' -- $line))
        end
    end
    test -n "$names[1]"; or return
    printf '%s\n' $names | sort -u
end

function __tmux_lives_removed_functions --argument-names old new --description 'pure: names present in the OLD newline-separated set and absent from the NEW one. Sourcing an update cannot UNSET a function, so these linger in every already-running shell — including the one that ran the update.'
    test -n "$old"; or return
    set -l newset (string split \n -- $new | string trim)
    for n in (string split \n -- $old | string trim)
        test -n "$n"; or continue
        contains -- $n $newset; or echo $n
    end
end

function __tmux_lives_stale_shells --description 'pure: session names of tmux pane shells other than our own. Args: <own pane pid> then `list-panes` lines of "<pane_pid> <session> <cmd>". fisher sources an update into the shell that ran it, so only the OTHERS are stale.'
    set -l own $argv[1]
    for line in $argv[2..]
        set -l f (string split ' ' -- $line)
        test (count $f) -ge 2; or continue
        test "$f[1]" = "$own"; and continue
        echo $f[2]
    end
end

function __tmux_lives_shell_is_idle --description 'True when this shell owns its terminal — no foreground child is running. Compares the ttys foreground process group against the shells own pgid: Linux reads /proc/<pid>/stat, macOS falls back to ps, mirroring the __tcz_pid_comm/__tcz_pid_cmdline split. With no controlling tty (tpgid -1) it returns FALSE ON PURPOSE: the only consumer is a notice printed to a live terminal, so "unsure" must mean "do not print". Known edge, accepted: a long-running fish FUNCTION or loop that forks no child holds fish own dispatch loop for that statements ENTIRE runtime, not a small window — fish will not invoke ANY handler, this one included, until it returns to a between-jobs checkpoint. That deferral, not this predicate, is what actually keeps a notice from landing mid-foreground-command; by the time any handler (and so this check) runs at all, fish itself already guarantees nothing else is in the foreground. What this predicate still covers is narrower: the no-tty case above, and whatever tty state exists at the moment dispatch does happen (verified against a real pty; see the task-1 report for the transcript).'
    set -l pid $fish_pid
    set -l tp ''
    set -l pg ''
    if test -r /proc/$pid/stat
        # comm (field 2) is parenthesised and may itself contain spaces, so strip
        # through the LAST ") " before splitting. What remains is
        # [1]=state [2]=ppid [3]=pgrp [4]=session [5]=tty_nr [6]=tpgid
        set -l rest (string replace -r '^.*\) ' '' < /proc/$pid/stat)
        set -l f (string split ' ' -- $rest)
        set pg "$f[3]"
        set tp "$f[6]"
    else
        set -l out (ps -o tpgid=,pgid= -p $pid 2>/dev/null | string trim | string split -n ' ')
        set tp "$out[1]"
        set pg "$out[2]"
    end
    # Guard the numeric compares: a non-numeric field would make `test -gt` error
    # to stderr, and this runs inside an event handler where that lands on the tty.
    string match -qr '^-?[0-9]+$' -- "$tp"; or return 1
    string match -qr '^-?[0-9]+$' -- "$pg"; or return 1
    test "$tp" -gt 0; or return 1
    test "$tp" = "$pg"
end

function __tmux_lives_shell_reload --on-variable tmux_lives_reload_token --description 'Re-source this plugins conf.d files in place when an update announces itself, in shells that are ALREADY RUNNING -- including ones whose foreground is Claude. A shell receiving a FOREIGN notification defers handler dispatch until control returns to its own main loop, so such a shell fires once whatever is in its foreground exits, not while it is running. NB narrower than it first reads: a set -U in the SAME shell fires its own handler INLINE, mid-statement (verified), which is why the updating shell re-sources redundantly and prints from inside the fisher job. See __tmux_lives_shell_is_idle for the corrected framing. Only the two conf.d files are re-sourced; the categorizer under functions/ is deliberately excluded because it is only ever invoked as a script, never autoloaded (see the design doc). NB that exclusion is asserted by a test that greps this function, so do NOT name that file literally here. This handler re-sources the very file that defines it, which re-registers this --on-variable binding mid-dispatch -- that, not a double-fire (no set -U was ever observed firing a shell twice; that was a measurement artefact and is retracted), is why the dedup marker below exists. Prints ONLY when the shell is idle: the handler shares its stdout with whatever is drawing on the tty.'
    status is-interactive; or return
    test "$tmux_lives_autoreload" = 0; and return
    # Re-sourcing tmux-lives-install.fish below redefines THIS function while it
    # is still running, re-registering the --on-variable binding mid-dispatch.
    # That is the real reason this must be idempotent -- see the docstring.
    test "$__tmux_lives_reloaded_at" = "$tmux_lives_reload_token"; and return
    set -g __tmux_lives_reloaded_at $tmux_lives_reload_token
    for f in $__fish_config_dir/conf.d/tmux.fish $__fish_config_dir/conf.d/tmux-lives-install.fish
        test -r $f; and source $f
    end
    __tmux_lives_shell_is_idle; or return
    echo '↻ tmux-lives reloaded'
    commandline -f repaint
end

function __tmux_lives_update_note --argument-names refreshed removed sessions autoreloaded --description 'pure: the post-update advice. `removed`/`sessions` are space-separated. exec fish is recommended HERE only when a function was removed (sourcing cannot unset one); other shells are named because exec fish does not reach them, unless `autoreloaded` (4th, optional) says they already re-sourced themselves.'
    if test "$refreshed" -eq 1
        echo '✓ tmux-lives updated — tmux config refreshed + reloaded.'
    else
        echo '✓ tmux-lives updated.'
    end
    set -l rm (string split ' ' -- $removed | string match -v '')
    set -l ss (string split ' ' -- $sessions | string match -v '')
    if test -n "$rm[1]"
        echo "  ⚠ removed: $rm — run `exec fish` here too (sourcing cannot unset a function)."
    end
    if test -n "$ss[1]"
        set -l uniq (printf '%s\n' $ss | sort -u | string join ', ')
        # Only claim this shell is current when nothing was removed — otherwise the two
        # lines contradict each other.
        if test "$autoreloaded" = 1; and test -z "$rm[1]"
            # NOT "already refreshed" -- fish defers ALL event-handler dispatch (this
            # includes the re-source) until control returns to its main loop, so a shell
            # busy running something in the foreground (e.g. Claude) hasn't re-sourced
            # yet at the moment this note prints; it will the instant that job exits.
            echo "  Other shells refreshed automatically (busy ones catch up once idle): $uniq"
        else if test "$autoreloaded" = 1
            # They re-sourced (or will, once idle), but sourcing cannot unset a function there either.
            echo "  Other shells refreshed automatically (busy ones catch up once idle): $uniq — but run `exec fish` in each, since the removal above cannot be sourced away."
        else if test -n "$rm[1]"
            echo "  Other shells also run the old version: $uniq — run `exec fish` in each."
        else
            echo "  This shell is current. Other shells still run the old version: $uniq — run `exec fish` in each."
        end
    end
end

function __tmux_lives_stale_sessions --description 'session names of tmux pane shells other than this one — the shells an update did NOT reach. Empty outside tmux or when tmux is unreachable.'
    # Build the invocation with an if/else, matching every other seam site in this
    # file (:698, :916, :1252). The variable form this used to carry was broken TWO
    # different ways, and both are worth recording because each looks fine:
    #   set -l tm "command tmux -L $sock"  -> fish does NOT word-split, so the whole
    #       string became the command name: `Unknown command: 'command tmux -L …'`
    #   set -l tm command tmux -L $sock    -> a correct list, but fish refuses a
    #       KEYWORD arriving via expansion: `The expanded command is a keyword.`
    # There is no variable form that works, which is why the rest of the file
    # spells the command out in both branches.
    set -l lines
    if set -q tmux_lives_tmux_socket
        set lines (command tmux -L $tmux_lives_tmux_socket list-panes -a -F '#{pane_pid} #{session_name} #{pane_current_command}' 2>/dev/null)
    else
        set lines (tmux list-panes -a -F '#{pane_pid} #{session_name} #{pane_current_command}' 2>/dev/null)
    end
    test -n "$lines[1]"; or return
    # Ask tmux which pane we are in rather than assuming fish is the pane's own shell —
    # it is not when this runs from a nested or non-login shell, and then our own session
    # would be reported as stale. Fall back to $fish_pid outside tmux.
    set -l own
    if set -q tmux_lives_tmux_socket
        set own (command tmux -L $tmux_lives_tmux_socket display-message -p '#{pane_pid}' 2>/dev/null)
    else
        set own (tmux display-message -p '#{pane_pid}' 2>/dev/null)
    end
    test -n "$own"; or set own $fish_pid
    __tmux_lives_stale_shells $own $lines
end

function __tmux_lives_baseline_template --description 'print the default ~/.tmux-lives.conf (status-bar polish + non-ShellFish baseline)'
    printf '%s\n' \
        '# ~/.tmux-lives.conf — your general tmux-lives config.' \
        '# Sourced when tmux-lives loads (every client) and re-applied when a NON-ShellFish' \
        "# client attaches. Edit freely; 'tmux-lives setup conf reset' restores these defaults." \
        '' \
        '# --- status bar ---' \
        '# Layout (session name, window list, clock caps) is owned by the managed fragment via' \
        "# status-format[0]; tune it live with 'tmux set -g @tmux_lives_*'. This file only carries" \
        '# the clock content + its length, which the fragment renders inside the right cap.' \
        'set -g status-right-length 60' \
        '# status-right content goes through this var so tmux-lives keeps the categorize tick' \
        '# + continuum autosave attached (it sets the actual status-right). 12h, month-first:' \
        'set -g @tmux_lives_status_right "%b %-d · %-I:%M %p "' \
        '' \
        '# --- non-ShellFish baseline (re-applied when a non-ShellFish client attaches) ---' \
        "# Settings ShellFish's integration forces that you want undone for other clients." \
        '# Example:' \
        '# set -g mouse off'
end

function __tmux_lives_seed_baseline --argument-names f --description 'create the baseline file from the template iff absent (never overwrites)'
    test -e $f; and return 0
    __tmux_lives_baseline_template > $f
end

function __tmux_lives_conf_source --argument-names f --description 'source the user conf into tmux (honors the tmux_lives_tmux_socket test seam)'
    if set -q tmux_lives_tmux_socket
        command tmux -L $tmux_lives_tmux_socket source-file $f 2>/dev/null
    else
        tmux source-file $f 2>/dev/null
    end
end

function __tmux_lives_conf_cmd --description 'tmux-lives setup conf [edit|add <tmux-command>|reset]: manage ~/.tmux-lives.conf'
    set -l f (__tmux_lives_baseline_path)
    switch "$argv[1]"
        case ''
            echo "baseline file: $f"
            if test -e $f
                cat $f
            else
                echo "(does not exist yet — run 'tmux-lives setup conf edit' to create it)"
            end
        case edit
            __tmux_lives_seed_baseline $f
            set -l ed $EDITOR
            test -n "$ed"; or set ed vi
            $ed $f
        case add
            if test (count $argv) -lt 2
                echo "usage: tmux-lives setup conf add <tmux-command>" >&2
                return 1
            end
            __tmux_lives_seed_baseline $f
            printf '%s\n' (string join ' ' $argv[2..]) >> $f
            __tmux_lives_conf_source $f
            echo "tmux-lives: added to $f"
        case reset
            set -l backed 0
            test -e $f; and cp $f "$f.bak"; and set backed 1
            __tmux_lives_baseline_template > $f
            __tmux_lives_conf_source $f
            if test $backed -eq 1
                echo "tmux-lives: restored defaults to $f (previous version saved to $f.bak)"
            else
                echo "tmux-lives: wrote default $f"
            end
        case '*'
            echo "tmux-lives setup conf: unknown option '$argv[1]'" >&2
            echo "usage: tmux-lives setup conf [edit|add <tmux-command>|reset]" >&2
            return 1
    end
end

function __tmux_lives_setup_help_lines --description 'tmux-lives setup help content (unframed; tightened to fit an 80-col frame)'
    printf '%s\n' \
        'install & configuration' \
        '' \
        'install, i                  wire ~/.tmux.conf + plugins (systemd on Linux)' \
        'verify, v                   check install health + switcher keys' \
        'teardown                    remove the wiring (plugin & TPM kept)' \
        'keys                        show the current switcher keys' \
        "  -p, --prefix-key <key>    prefix-table bind (default: S; '' off)" \
        "  -s, --switcher-key <key>  no-prefix bind (default: M-s = Opt+s; '' off)" \
        "      --modal-key <key>     in-tmux command modal (default: M-m; '' off)" \
        "      --scratch-key <key>   scratch-split toggle (default: M-t; '' off)" \
        "      --resize-key <key>    scratch resize mode (default: M-r; '' off)" \
        "      --status-pos-key <key> status bar top/bottom (default: C-M-a; '' off)" \
        "      --status-vis-key <key> status bar hide/show  (default: C-M-s; '' off)" \
        "      --theme-key <key>     theme picker (default: M-k; '' off)" \
        'auto on|off|toggle|status   auto-attach to tmux on SSH login' \
        'color [<css>] [-i] [-a]     ShellFish tab/status; -i darker, -a reapply' \
        'theme [<rel>|list|off]      seed-based bar theme; no-arg=picker' \
        "      --place <p>           bar|tabs|cap (default: bar)" \
        "      --mode <m>            literal|derived (default: derived)" \
        "      --phase <deg>         rotate the hue arc (default: 0)" \
        'conf [edit|add|reset]       manage ~/.tmux-lives.conf (reset=defaults)'
end

function __tmux_lives_setup_help --description 'tmux-lives setup command list'
    __tmux_lives_setup_help_lines | __tmux_lives_box 'tmux-lives setup'
end

function __tmux_lives_setup_dispatch
    switch "$argv[1]"
        case '' help -h --help
            __tmux_lives_setup_help
        case install i
            __tmux_lives_setup
        case verify v
            echo "tmux-lives verify:"
            __tmux_lives_status_lines | sed 's/^/  /'
        case teardown
            __tmux_lives_teardown
        case keys
            __tmux_lives_keys_cmd $argv[2..]
        case color
            __tmux_lives_color_cmd $argv[2..]
        case theme
            __tmux_lives_theme_cmd $argv[2..]
        case conf
            __tmux_lives_conf_cmd $argv[2..]
        case auto
            __tmux_lives_auto $argv[2..]
        case '*'
            echo "tmux-lives setup: unknown command '$argv[1]'" >&2
            __tmux_lives_setup_help >&2
            return 1
    end
end

function __tmux_lives_digest --description 'cksum over the given files (tmux-lives update change-detection)'
    cat $argv 2>/dev/null | cksum
end

function __tmux_lives_update --description 'Update the tmux-lives plugin via fisher; stay quiet unless something changed'
    if not type -q fisher
        echo 'tmux-lives update: fisher not found — install fisher, or update manually' >&2
        return 1
    end
    # installed plugin files to watch for changes (overridable in tests)
    set -l files $tmux_lives_update_files
    test -n "$files"; or set files \
        $__fish_config_dir/conf.d/tmux.fish \
        $__fish_config_dir/conf.d/tmux-lives-install.fish \
        $__fish_config_dir/functions/tmux-categorize.fish
    set -l before (__tmux_lives_digest $files)
    # fisher reinstalls (and is noisy) on every update — divert its output to a file
    # (a redirect, NOT a `(…)` capture: that would break fisher's background-job fetch)
    # and only surface it if something actually changed, or if it failed.
    set -l log (mktemp)
    set -g _tmux_lives_updating 1   # silence the generic post-update note; we report below
    fisher update bit-saver/tmux-lives >$log 2>&1
    set -l rc $status
    set -e _tmux_lives_updating
    # The handler (which ran synchronously above, mid-`fisher update`) leaves the
    # autoreload verdict here for us -- see its docstring for why it can't just be
    # recomputed after the fact. Read it once and erase it immediately: `set -e` on an
    # unset var is silent (verified), so this is safe even when fisher failed before
    # the handler ran (rc -ne 0 below), and it can never leak into the next invocation.
    set -l autoreloaded 0
    set -q _tmux_lives_autoreloaded; and set autoreloaded $_tmux_lives_autoreloaded
    set -e _tmux_lives_autoreloaded
    if test $rc -ne 0
        cat $log >&2                # surface fisher's error
        rm -f $log
        return $rc
    end
    if test "$before" = (__tmux_lives_digest $files)
        echo 'tmux-lives: already up to date.'
    else
        cat $log                    # release fisher's output — something changed
        # The post-update handler already ran (fisher fired the event mid-`fisher update`)
        # and recorded the new function set, so removals are reported from there. Here we
        # only need to say which OTHER shells the update did not reach, and whether they
        # already refreshed themselves (autoreloaded, handed over above).
        __tmux_lives_update_note 0 "" "$(__tmux_lives_stale_sessions)" $autoreloaded
    end
    rm -f $log
end

function tmux-lives --description 'tmux-lives: unified command — setup/update/new/attach/picker/fix/clear/close'
    set -l cmd $argv[1]
    switch "$cmd"
        case '' help -h --help
            __tmux_lives_help
        case picker p
            __tmux_lives_picker $argv[2..]
        case attach a
            __tmux_lives_attach $argv[2..]
        case new n
            __tmux_lives_new $argv[2..]
        case close x q
            __tmux_lives_close
        case clear
            __tmux_lives_clear $argv[2..]
        case fix f
            __tmux_lives_fix
        case update u
            __tmux_lives_update
        case categorize c
            __tmux_categorize
        case setup
            __tmux_lives_setup_dispatch $argv[2..]
        case install i verify v teardown keys auto color conf
            # hidden shortcut: setup subcommands also work at top level (kept out of help)
            __tmux_lives_setup_dispatch $argv
        case '*'
            echo "tmux-lives: unknown command '$cmd'" >&2
            __tmux_lives_help >&2
            return 1
    end
end

function _tmux_lives_post_install --on-event tmux-lives-install_install --description 'Post-install guidance'
    printf '%s\n' \
        '✓ tmux-lives installed. One command finishes setup:' \
        '    tmux-lives setup install' \
        '  (wires tmux + plugins, then reloads tmux). '(__tmux_lives_help_hint)
end

function __tmux_lives_fragment_path --description 'path to the generated managed fragment (seam: tmux_lives_fragment_file)'
    set -q tmux_lives_fragment_file; and echo $tmux_lives_fragment_file; or echo "$HOME/.config/tmux/tmux-lives.conf"
end

function __tmux_lives_migrate_v2 --description 'one-time v2 cap -> v3 theme universal migration (idempotent; runs on fisher update). Reset-to-mono policy: geometric schemes have no arc equivalent.'
    set -l oldscheme ''
    set -q tmux_lives_cap; and set oldscheme $tmux_lives_cap
    if set -q tmux_lives_cap_key; and not set -q tmux_lives_theme_key
        set -U tmux_lives_theme_key $tmux_lives_cap_key
    end
    for old in tmux_lives_cap tmux_lives_cap_vividness tmux_lives_cap_wheel tmux_lives_cap_role tmux_lives_cap_key
        set -q $old; and set -e $old
    end
    test -n "$oldscheme"; and echo "tmux-lives: cap scheme '$oldscheme' has no v3 equivalent — theme is mono; tune with 'tmux-lives setup theme'"
    return 0
end

function __tmux_lives_migrate_v31 --description 'v3 -> v3.1 seed-anchored migration: polarity/range have no v3.1 meaning (the bar IS the seed; contrast defaults auto) — erase them (idempotent)'
    set -l had 0
    for old in tmux_lives_theme_polarity tmux_lives_theme_range
        set -q $old; and begin; set -e $old; set had 1; end
    end
    test $had -eq 1; and echo "tmux-lives: theme is now seed-anchored — polarity/range retired ('tmux-lives setup theme')"
    return 0
end

function __tmux_lives_migrate_v4 --description 'idempotent on fisher update: preserve the seed, retire tmux_lives_theme_rotate, and map a retired v3 scheme name onto v4 (mono/bar/derived). One notice when it changes anything.'
    set -l changed 0
    if set -q tmux_lives_theme_rotate
        set -e tmux_lives_theme_rotate
        set changed 1
    end
    if set -q tmux_lives_theme
        if test "$tmux_lives_theme" != off; and not contains -- "$tmux_lives_theme" (__tmux_lives_theme_relationships)
            set -U tmux_lives_theme mono
            set -U tmux_lives_theme_place bar
            set -U tmux_lives_theme_mode derived
            set changed 1
        end
    end
    test $changed -eq 1; and echo "tmux-lives: theme migrated to v4 (relationships + placement); your seed color is preserved — see 'tmux-lives setup theme list'"
end

function __tmux_lives_migrate_v41 --description 'v4 -> v5 big-area migration: --place low|high meant "partway along the curve", and the big-area model has no curve to sit partway along — the seed anchors a large area (or the endcap). Rewrite a stored low/high to bar. Idempotent; runs on fisher update.'
    set -q tmux_lives_theme_place; or return 0
    contains -- "$tmux_lives_theme_place" low high; or return 0
    set -U tmux_lives_theme_place bar
    echo "tmux-lives: theme place low/high retired — the seed now anchors a large area; set to bar (see 'tmux-lives setup theme list')"
    return 0
end

function __tmux_lives_migrate_v51 --description 'v5 -> v5.1: vividness/shape/ease/contrast were accepted, stored and displayed but never reached the curve — verified byte-identical output across all 35 catalog rows at every value. Erase them; there is no value worth carrying because no value ever meant anything. Idempotent; runs on fisher update.'
    set -l had 0
    for v in tmux_lives_theme_vividness tmux_lives_theme_shape tmux_lives_theme_ease tmux_lives_theme_contrast
        if set -q $v
            # NOT `set -e -U`: under `fish --no-config` that silently fails to erase (the
            # universal store isn't live there) while the variable stays visibly set —
            # reproduced directly, and the sibling migrations (v2/v31/v4) already erase
            # scope-less for the same reason. A scope-less `set -e` erases whichever scope
            # the name is found in and works in both modes.
            set -e $v
            set had 1
        end
    end
    test $had -eq 1; and echo "tmux-lives: theme vividness/shape/ease/contrast retired — they never affected the output"
    return 0
end

function __tmux_lives_migrate_v52 --description 'v5.1 -> v5.2: auto-apply-on-dwell (theme-picker A toggle) is retired outright — the user tried it live and found it too disruptive, not merely defaulted off — so tmux_lives_theme_autoapply is now dead weight if a session ever pressed A. Erase it, scope-less like v51 (a scoped `set -e -U` silently no-ops under `fish --no-config`). Idempotent; runs on fisher update.'
    set -q tmux_lives_theme_autoapply; or return 0
    set -e tmux_lives_theme_autoapply
    echo "tmux-lives: theme-picker auto-apply retired — press a or ⏎ to apply a scheme"
    return 0
end

function _tmux_lives_post_update --on-event tmux-lives-install_update --description 'Post-update: re-render the fragment (if set up) so new wiring lands, then note'
    # `fisher update` refreshes the plugin CODE but not the generated fragment. If this host
    # has been set up (the fragment exists), re-render it so new wiring (e.g. the client-attached
    # hook) lands without a manual `tmux-lives setup` — then reload tmux.
    __tmux_lives_migrate_v2
    __tmux_lives_migrate_v31
    __tmux_lives_migrate_v4
    __tmux_lives_migrate_v41
    __tmux_lives_migrate_v51
    __tmux_lives_migrate_v52
    set -l refreshed 0
    if test -e (__tmux_lives_fragment_path)
        __tmux_lives_write_fragment
        set refreshed 1
    end
    # Record which functions this version ships, so the NEXT update can spot removals.
    # fisher sources the new files into this shell, so a removed name would otherwise
    # linger here silently.
    set -l removed (__tmux_lives_removed_functions (__tmux_lives_read_funcs) (__tmux_lives_shipped_functions | string join \n))
    __tmux_lives_write_funcs
    # Announce the update to every other running shell. MUST sit above the
    # `_tmux_lives_updating` early return: below it, plain `fisher update` would
    # refresh other shells while `tmux-lives update` silently would not, and the
    # divergence would be invisible until someone noticed the two paths disagree.
    # The event fires even when the value is unchanged (measured), so the digest
    # comparison here is the only thing stopping a no-op update — and fisher
    # always re-fetches, so no-op updates are the common case — from refreshing
    # every shell and printing in every idle one.
    set -l files $tmux_lives_update_files
    test -n "$files"; or set files \
        $__fish_config_dir/conf.d/tmux.fish \
        $__fish_config_dir/conf.d/tmux-lives-install.fish \
        $__fish_config_dir/functions/tmux-categorize.fish
    set -l dg (__tmux_lives_digest $files)
    set -l had ''
    set -q tmux_lives_reload_token; and set had $tmux_lives_reload_token
    set -l autoreloaded 0
    if test "$dg" != "$had"
        # A previously-set token means the other shells carry the handler. An
        # ABSENT one means this is the first update shipping the feature, so they
        # do not — and the old `exec fish` advice is still correct for them.
        # tmux_lives_autoreload is a universal opt-out, shared by every one of the
        # user's shells including this one (see __tmux_lives_shell_reload) -- when
        # it's 0, no shell's handler will actually re-source on this token bump,
        # so the note must not claim they did. The token itself still bumps
        # either way (harmless: every handler no-ops on it while opted out, and
        # it's what a later opt-back-in would want to already reflect).
        if test -n "$had"; and test "$tmux_lives_autoreload" != 0
            set autoreloaded 1
        end
        set -U tmux_lives_reload_token $dg
    end
    if set -q _tmux_lives_updating
        # `tmux-lives update` reports the result itself (below, via __tmux_lives_update),
        # but $autoreloaded is a local here and gone by the time that call runs -- fisher
        # has already returned and this function has already returned with it. Hand it
        # over the same way `_tmux_lives_updating` itself is handed the OTHER direction:
        # a plain global the wrapper reads once and erases immediately, so it can never
        # leak past this one `tmux-lives update` invocation or go stale for the next.
        # This runs every time (the event fires even on a no-op update, per above), so
        # it is always the CURRENT $autoreloaded -- 0 on a no-op, never a leftover 1.
        set -g _tmux_lives_autoreloaded $autoreloaded
        return
    end
    __tmux_lives_update_note $refreshed "$removed" "$(__tmux_lives_stale_sessions)" $autoreloaded
    __tmux_lives_help_hint
end

function __tmux_lives_read_funcs --description 'the function-name record from the previous update, or empty on first run'
    set -l p (__tmux_lives_funcs_path)
    test -f $p; and cat $p
end

function __tmux_lives_write_funcs --description 'record the function names this version ships, for the next update to diff against'
    set -l p (__tmux_lives_funcs_path)
    mkdir -p (path dirname $p) 2>/dev/null
    __tmux_lives_shipped_functions > $p 2>/dev/null
end
