# tmux-lives install/uninstall/status. All functions live here (one conf.d file
# per feature). No startup trigger — these are user-invoked commands.

# module-scope constant for the OKLCH conversion core below (__tmux_lives_rgb_to_oklch /
# __tmux_lives_oklch_to_linrgb use it for the atan2/cos/sin hue math).
set -q __tmux_lives_pi; or set -g __tmux_lives_pi (math "atan2(0, -1)")

function __tmux_lives_key --description 'Effective switcher key: VARNAME unset -> DEFAULT; set (even empty) -> its value'
    set -l name $argv[1]
    set -q $name; or begin; echo $argv[2]; return; end
    echo $$name
end

function __tmux_lives_render_fragment --description 'Emit the tmux.conf fragment (categorizer path + switcher key binds)'
    # $cat is interpolated unquoted into nested tmux+sh quote layers; assumes no spaces.
    set -l cat $argv[1]
    set -l pkey $argv[2]   # prefix-table key ('' = no prefix bind)
    set -l skey $argv[3]   # no-prefix/direct key ('' = no direct bind)
    set -l color $argv[4]  # ShellFish bar color baked into the client-attached hook ('' = none)
    set -l invert $argv[5]  # 1 = darker status bar; else lighter
    set -l modalkey $argv[6]   # root-table modal key ('' = no bind)
    set -l scratchkey $argv[7] # root-table scratch-toggle key ('' = no bind)
    set -l resizekey $argv[8]   # root-table scratch-resize-mode key ('' = no bind)
    set -l statusposkey $argv[9]   # root-table status-position toggle ('' = no bind)
    set -l statusviskey $argv[10]  # root-table status-visibility toggle ('' = no bind)
    set -l cursorstyle $argv[11]   # steady cursor-style (block|bar|underline) to stop the ShellFish cursor flicker; '' = leave tmux's default. See [[shellfish-cursor-flicker]].
    set -l themekey $argv[12]     # root-table theme-picker key ('' = no bind)
    set -l theme $argv[13]        # v3 scheme ('' or 'off' = legacy; write_fragment passes the effective default mono)
    set -l themephase $argv[14]   # hue phase in degrees ('' = 0)
    set -l themeviv $argv[15]     # soft|balanced|vivid ('' = balanced)
    set -l themeshape $argv[16]   # arc|flat ('' = arc)
    set -l themeease $argv[17]    # linear|cubic ('' = linear)
    set -l themecontrast $argv[18]   #   18 themecontrast  companion side auto|lighter|darker ('' = auto)
    set -l themerotate $argv[19]   #   19 themerotate    companion placement rotation 0-4 ('' = 0)
    test "$theme" = off; and set theme ''
    set -l baseline (__tmux_lives_baseline_path)
    set -l state (__tmux_lives_state_path)
    set -l popup
    set -l menu
    if test -n "$pkey"
        set -a popup "    bind-key $pkey display-popup -E -w 80% -h 70% -- fish --no-config $cat popup '#{client_name}'"
        set -a menu  "    bind-key $pkey run-shell 'fish --no-config $cat menu'"
    end
    if test -n "$skey"
        set -a popup "    bind-key -n $skey display-popup -E -w 80% -h 70% -- fish --no-config $cat popup '#{client_name}'"
        set -a menu  "    bind-key -n $skey run-shell 'fish --no-config $cat menu'"
    end
    if test -n "$modalkey"
        set -a popup "    bind-key -n $modalkey display-popup -B -E -w 34 -h 15 -- fish --no-config $cat modal '#{client_name}' '$modalkey' '$scratchkey' '$resizekey' '$skey'"
        set -a menu  "    bind-key -n $modalkey run-shell 'fish --no-config $cat modal-menu'"
    end
    set -l f
    set -a f "# tmux-lives — managed fragment. Generated by 'tmux-lives setup'; edit the plugin, not this."
    set -a f "set -g @plugin 'tmux-plugins/tmux-resurrect'"
    set -a f "set -g @plugin 'tmux-plugins/tmux-continuum'"
    set -a f "set -g @resurrect-strategy-nvim 'session'"
    set -a f "set -g @resurrect-strategy-vim  'session'"
    set -a f "set -g @resurrect-capture-pane-contents 'on'"
    set -a f "set -g @continuum-save-interval '15'"
    set -a f "set -g status-interval 15"
    # Pin a STEADY cursor so tmux's cstyle re-emission on redraw doesn't flicker the ShellFish
    # cursor (a steady style re-emitted is invisible). '' leaves tmux's default untouched.
    test -n "$cursorstyle"; and set -a f "set -g cursor-style $cursorstyle"
    set -a f "# macOS reports claude's version-named binary (versions/X.Y.Z) as the window"
    set -a f "# command; show 'claude' for a version-like name, pass everything else through."
    set -a f "set -g automatic-rename-format '#{?pane_in_mode,[tmux],#{?#{m:*.*.*,#{pane_current_command}},claude,#{pane_current_command}}}#{?pane_dead,[dead],}'"
    # Source the user's general config (~/.tmux-lives.conf) if present — applies to every
    # client at load (and is re-sourced on non-ShellFish attach). The baseline sets the clock
    # @var (@tmux_lives_status_right) + status-right-length; layout (window list, identity, caps) now lives in status-format[0] below.
    set -a f "set -g @tmux_lives_status_right \"%-I:%M %p · %b %-d \""
    set -a f "if-shell '[ -f $baseline ]' 'source-file $baseline'"
    # status-right = the time format via #{T:@var} (so strftime applies) + our tick.
    # continuum prepends its autosave hook when TPM runs. The user's file sets only the
    # @var, never status-right, so a re-source can't wipe the tick/continuum.
    set -a f "set -g status-right \"#{T:@tmux_lives_status_right}#(fish --no-config $cat tick '$color')\""
    # --- theme engine v3 (gradient map, Phase 1): with a scheme in argv[13] the whole bar
    # renders from the 7-role gradient palette (bar sep tabs active windows cap text);
    # otherwise the v2 path is unchanged. Role->t lives in __tmux_lives_theme_roles.
    set -l tpal
    if test -n "$theme"
        set -l seedhex (__tmux_lives_seed_hex $color)
        test -n "$seedhex"; and set tpal (__tmux_lives_theme_palette $seedhex "$theme" "$themephase" "$themeviv" "$themeshape" "$themeease" "$themecontrast" "$themerotate")
    end
    set -l themed 0
    test (count $tpal) -eq 7; and set themed 1
    if test $themed -eq 1
        # bar (t=0) is the trough bg; windows (t=.60) is the base fg all inactive names inherit
        set -a f "set -g status-style bg=$tpal[1],fg=$tpal[5]"
    else
        set -l ss (__tmux_lives_derive_status $color $invert)
        test -n "$ss"; and set -a f "set -g status-style $ss"
    end
    # --- status bar overhaul: names-only window list, @option-driven caps, status-format[0] ---
    # Layout lives in status-format[0] (built by the categorizer's pure `status-format` verb);
    # every knob is a live-tunable @option so `tmux set -g @tmux_lives_*` retints with no re-render.
    # tint the auto-named `claude` window in @tmux_lives_claude_color; reset fg after so the
    # separator / other windows are unaffected. Position unchanged; current stays bold.
    # The current window name + separator wear the v3 text/sep roles; the v2 path seeds those
    # @options to 'default' (a no-op style) so the pre-theme look is unchanged.
    set -a f "set -g window-status-format '#{?#{==:#{window_name},claude},#[fg=#{@tmux_lives_claude_color}]#W#[fg=default],#W}'"
    set -a f "set -g window-status-current-format '#[bold]#{?#{==:#{window_name},claude},#[fg=#{@tmux_lives_claude_color}]#W#[fg=default],#[fg=#{@tmux_lives_text_fg}]#W#[fg=default]}#[nobold]'"
    set -a f "set -g window-status-separator ' #[fg=#{@tmux_lives_sep_fg}]•#[fg=default] '"
    # cap/accent colors. Themed: bar/cap are gradient samples. Legacy (theme off / no usable
    # seed): bar bg = the ShellFish-derived status bg; the cap is a flat neutral (the v2
    # geometric-harmony engine that used to pick a role color here is gone).
    set -l barbg
    set -l capbg
    if test $themed -eq 1
        set barbg $tpal[1]
        set capbg $tpal[6]
    else
        set barbg (__tmux_lives_derive_status_bg $color $invert)   # the bar's own bg (status-style bg)
        test -n "$barbg"; or set barbg colour236
        set capbg colour238   # legacy neutral cap (theme off / no usable seed)
    end
    set -l capfg (__tmux_lives_contrast_fg $capbg)                # readable fg for whichever cap shade/hue was picked
    # QUOTE the values: an unquoted #rrggbb hex is read as a tmux COMMENT (option set to empty). Single
    # quotes keep the '#5793f0' bg intact (harmless around the colourNNN default too).
    set -a f "set -g @tmux_lives_bar_bg '$barbg'"                 # slant transition target (cap -> bar)
    set -a f "set -g @tmux_lives_cap_bg '$capbg'"
    set -a f "set -g @tmux_lives_cap_fg '$capfg'"
    if test $themed -eq 1
        set -a f "set -g @tmux_lives_sep_fg '$tpal[2]'"           # sep role (t=.32): the • separators
        set -a f "set -g @tmux_lives_tabs_color '$tpal[3]'"       # tabs role (t=.45): Phase 2 wires the ShellFish OSC
        set -a f "set -g @tmux_lives_active_fg '$tpal[4]'"        # active role (t=.55): provisional, unconsumed
        set -a f "set -g @tmux_lives_mark_fg '$tpal[6]'"          # the ✦ identity mark wears the cap sample
        set -a f "set -g @tmux_lives_text_fg '$tpal[7]'"          # text role (t=1.0): current window + centre identity
    else
        set -a f "set -g @tmux_lives_sep_fg default"
        set -a f "set -g @tmux_lives_tabs_color ''"
        set -a f "set -g @tmux_lives_active_fg default"
        set -a f "set -g @tmux_lives_mark_fg default"
        set -a f "set -g @tmux_lives_text_fg default"
    end
    set -a f "set -g @tmux_lives_prefix_color colour214"
    set -a f "set -g @tmux_lives_resize_color colour208"
    set -a f "set -g @tmux_lives_claude_color '#D97757'"   # Claude coral; static, independent of the ShellFish bar color
    set -a f "set -g @tmux_lives_heal_interval 120"        # color-only self-heal backstop seconds (0 = off)
    set -a f "set -g @tmux_lives_glyph_remote '"(printf '\U0000eb3a')"'"   # cod-remote
    set -a f "set -g @tmux_lives_glyph_local '"(printf '\U0000ea7a')"'"    # cod-vm
    # host-kind + status-format are computed at RENDER time by the categorizer (pure verbs).
    # Compute into a pre-declared var FIRST: a bad/absent $cat (e.g. a test's fake path) makes
    # the substitution fail, which would skip an inline `set -a f "..."(…)` statement entirely
    # (a broken fragment). This form leaves the var empty so the option line is still emitted
    # (empty value). 2>/dev/null keeps a bad path from leaking "No such file" to stderr.
    set -l hostkind ""; set hostkind (fish --no-config $cat host-kind 2>/dev/null)
    set -l sfmt ""; set sfmt (fish --no-config $cat status-format 2>/dev/null)
    set -a f "set -g @tmux_lives_host_kind '$hostkind'"
    set -a f "set -g @tmux_lives_claude ''"
    set -a f "set -g status-format[0] \"$sfmt\""
    # reapply the persisted status-position/visibility (written by the C-M-a/C-M-s toggles)
    set -a f "if-shell '[ -f $state ]' 'source-file $state'"
    if test -n "$popup"
        set -a f "if-shell 'tmux list-commands 2>/dev/null | grep -q display-popup' {"
        set -a f $popup
        set -a f "} {"
        set -a f $menu
        set -a f "}"
    end
    test -n "$scratchkey"; and set -a f "bind-key -n $scratchkey run-shell 'fish --no-config $cat scratch'"
    test -n "$themekey"; and set -a f "bind-key -n $themekey display-popup -B -E -w 52 -h 27 -- fish --no-config $cat theme-picker '#{client_name}'"
    if test -n "$resizekey"
        set -a f "bind-key -n $resizekey run-shell \"fish --no-config $cat resize-enter '#{client_name}'\""
        set -a f "bind-key -T tmuxlives-resize Left  { run-shell \"fish --no-config $cat scratch-resize L\" ; switch-client -T tmuxlives-resize }"
        set -a f "bind-key -T tmuxlives-resize Right { run-shell \"fish --no-config $cat scratch-resize R\" ; switch-client -T tmuxlives-resize }"
        set -a f "bind-key -T tmuxlives-resize Up    { run-shell \"fish --no-config $cat scratch-resize U\" ; switch-client -T tmuxlives-resize }"
        set -a f "bind-key -T tmuxlives-resize Down  { run-shell \"fish --no-config $cat scratch-resize D\" ; switch-client -T tmuxlives-resize }"
        set -a f "bind-key -T tmuxlives-resize h     { run-shell \"fish --no-config $cat scratch-orient h\" ; switch-client -T tmuxlives-resize }"
        set -a f "bind-key -T tmuxlives-resize w     { run-shell \"fish --no-config $cat scratch-orient w\" ; switch-client -T tmuxlives-resize }"
        set -a f "bind-key -T tmuxlives-resize x       run-shell \"fish --no-config $cat scratch-kill\""
        set -a f "bind-key -T tmuxlives-resize Escape  switch-client -T root"
        set -a f "bind-key -T tmuxlives-resize Enter   switch-client -T root"
    end
    test -n "$statusposkey"; and set -a f "bind-key -n $statusposkey run-shell 'fish --no-config $cat status-pos-toggle'"
    test -n "$statusviskey"; and set -a f "bind-key -n $statusviskey run-shell 'fish --no-config $cat status-vis-toggle'"
    set -a f "set-hook -g client-session-changed {"
    set -a f "    run-shell \"fish --no-config $cat retitle\""
    set -a f "    if-shell -F '#{m:shellfish-*,#{client_session}}' {"
    set -a f "        run-shell \"fish --no-config $cat commandeer '#{client_name}' '#{client_session}'\""
    set -a f "    }"
    set -a f "}"
    set -a f "set-hook -g client-attached {"
    set -a f "    run-shell \"fish --no-config $cat on-attach '#{client_pid}' '#{client_tty}' '$color'\""
    set -a f "}"
    set -a f "set -ga update-environment \"LC_TERMINAL\""
    set -a f "set -ga update-environment \"LC_TERMINAL_VERSION\""
    set -a f "# Load declared plugins via TPM (setup clones them); without this they are"
    set -a f "# present but never sourced — no resurrect save/restore, no continuum autosave."
    set -a f "run '~/.tmux/plugins/tpm/tpm'"
    printf '%s\n' $f
end

function __tmux_lives_save_unit_text --description 'systemd save-on-shutdown unit text'
    set -l user $argv[1]; set -l uid $argv[2]
    printf '%s\n' \
        "[Unit]" \
        "Description=Save user tmux sessions (resurrect) before shutdown" \
        "DefaultDependencies=no" "Before=shutdown.target" \
        "After=user@$uid.service" "Conflicts=shutdown.target" "" \
        "[Service]" "Type=oneshot" "RemainAfterExit=yes" "ExecStart=/usr/bin/true" \
        "ExecStop=/usr/bin/su - $user -c 'tmux run-shell ~/.tmux/plugins/tmux-resurrect/scripts/save.sh'" "" \
        "[Install]" "WantedBy=multi-user.target"
end

function __tmux_lives_restore_unit_text --description 'systemd restore-at-boot unit text'
    set -l user $argv[1]; set -l uid $argv[2]
    printf '%s\n' \
        "[Unit]" "Description=Restore user tmux sessions (resurrect) at boot" \
        "After=multi-user.target user@$uid.service" "" \
        "[Service]" "Type=oneshot" \
        "ExecStart=/usr/bin/su - $user -c 'fish -c __tmux_restore'" "" \
        "[Install]" "WantedBy=multi-user.target"
end

function __tmux_lives_ensure_source_line --description 'Idempotently source the fragment before the TPM run-line'
    set -l tmux_conf $argv[1]; set -l fragment $argv[2]
    set -l line "source-file $fragment"
    test -f $tmux_conf; or touch $tmux_conf
    grep -qF -- "$line" $tmux_conf; and return 0
    if grep -q "tpm/tpm" $tmux_conf
        set -l tmp (mktemp)
        awk -v L="$line" '/tpm\/tpm/ && !d {print L; d=1} {print}' $tmux_conf > $tmp
        mv $tmp $tmux_conf
    else
        printf '%s\n' "$line" >> $tmux_conf
    end
end

function __tmux_lives_persistence_note --description 'macOS/non-systemd persistence model (for tmux-lives setup)'
    echo "no systemd — persistence via continuum autosave + restore on first SSH login"
end

function __tmux_lives_persistence_status --description 'macOS/non-systemd persistence status line'
    echo "OK persistence via continuum autosave + first-access restore"
end

function __tmux_lives_reload --description 'source the tmux config into a running server (no-op if none)'
    set -l conf $argv[1]
    test -n "$conf"; or set conf "$HOME/.tmux.conf"
    # No server yet (fresh host): nothing to reload — the fragment loads when tmux starts.
    tmux list-sessions >/dev/null 2>&1; or return 0
    tmux source-file "$conf" 2>/dev/null
end

function __tmux_lives_write_fragment --description 'Render the managed fragment, wire ~/.tmux.conf, reload tmux'
    set -l cat "$__fish_config_dir/functions/tmux-categorize.fish"
    # Defense-in-depth: never render/wire/reload a fragment whose categorizer path
    # does not exist (e.g. a stray call with a test's temp $__fish_config_dir). Returning
    # here — before any write — keeps a rogue event from corrupting the live fragment.
    test -f $cat; or return
    set -l tmuxdir "$HOME/.config/tmux"
    set -l fragment "$tmuxdir/tmux-lives.conf"
    mkdir -p $tmuxdir
    __tmux_lives_render_fragment $cat (__tmux_lives_key tmux_lives_prefix_key S) (__tmux_lives_key tmux_lives_switcher_key M-s) (__tmux_lives_key tmux_lives_bar_color '') (__tmux_lives_key tmux_lives_status_invert 0) (__tmux_lives_key tmux_lives_modal_key M-m) (__tmux_lives_key tmux_lives_scratch_key M-t) (__tmux_lives_key tmux_lives_resize_key M-r) (__tmux_lives_key tmux_lives_status_pos_key C-M-a) (__tmux_lives_key tmux_lives_status_vis_key C-M-s) (__tmux_lives_key tmux_lives_cursor_style block) (__tmux_lives_key tmux_lives_theme_key M-k) (__tmux_lives_key tmux_lives_theme mono) (__tmux_lives_key tmux_lives_theme_phase 0) (__tmux_lives_key tmux_lives_theme_vividness balanced) (__tmux_lives_key tmux_lives_theme_shape arc) (__tmux_lives_key tmux_lives_theme_ease linear) (__tmux_lives_key tmux_lives_theme_contrast auto) (__tmux_lives_key tmux_lives_theme_rotate 0) > $fragment
    __tmux_lives_ensure_source_line "$HOME/.tmux.conf" $fragment
    __tmux_lives_reload
end

function __tmux_lives_setup --description 'tmux-lives: install fragment + tmux.conf wiring + TPM plugins + systemd units'
    set -l tmuxdir "$HOME/.config/tmux"
    set -l fragment "$tmuxdir/tmux-lives.conf"

    set -l tpm "$HOME/.tmux/plugins/tpm"
    test -d $tpm; or git clone -q https://github.com/tmux-plugins/tpm $tpm
    for p in tmux-resurrect tmux-continuum
        set -l d "$HOME/.tmux/plugins/$p"
        test -d $d; or git clone -q https://github.com/tmux-plugins/$p $d
    end
    echo "tmux-lives setup: TPM + resurrect + continuum present"

    __tmux_lives_write_fragment
    echo "tmux-lives setup: wrote $fragment"
    echo "tmux-lives setup: ensured source-file line in ~/.tmux.conf"

    __tmux_lives_seed_baseline (__tmux_lives_baseline_path)
    echo "tmux-lives setup: baseline file at "(__tmux_lives_baseline_path)" (edit: tmux-lives setup conf edit)"

    if type -q systemctl
        set -l user (id -un); set -l uid (id -u)
        echo "tmux-lives setup: installing systemd units (sudo required)…"
        __tmux_lives_save_unit_text $user $uid | sudo tee /etc/systemd/system/tmux-resurrect-save.service >/dev/null
        __tmux_lives_restore_unit_text $user $uid | sudo tee /etc/systemd/system/tmux-resurrect-restore.service >/dev/null
        sudo systemctl daemon-reload
        sudo systemctl enable --now tmux-resurrect-save.service
        sudo systemctl enable tmux-resurrect-restore.service
        echo "tmux-lives setup: systemd units installed + enabled"
    else
        echo "tmux-lives setup: "(__tmux_lives_persistence_note)
    end
    set -l had_server 0
    tmux list-sessions >/dev/null 2>&1; and set had_server 1
    if test $had_server -eq 1
        echo "tmux-lives setup: done — reloaded the running tmux; the switcher + persistence are live now."
    else
        echo "tmux-lives setup: done — start tmux to load the fragment."
    end
    echo "tmux-lives setup: run 'tmux-lives setup verify' anytime to check the install."
end

function __tmux_lives_remove_source_line --description 'Remove the fragment source-file line'
    set -l tmux_conf $argv[1]; set -l fragment $argv[2]
    test -f $tmux_conf; or return 0
    set -l tmp (mktemp)
    grep -vF -- "source-file $fragment" $tmux_conf > $tmp
    mv $tmp $tmux_conf
end

function __tmux_lives_teardown --description 'tmux-lives: remove fragment + tmux.conf wiring + systemd units'
    set -l fragment "$HOME/.config/tmux/tmux-lives.conf"
    __tmux_lives_remove_source_line "$HOME/.tmux.conf" $fragment
    rm -f $fragment
    echo "tmux-lives teardown: removed fragment + source-file line"
    if type -q systemctl
        echo "tmux-lives teardown: removing systemd units (sudo)…"
        sudo systemctl disable --now tmux-resurrect-save.service 2>/dev/null
        sudo systemctl disable tmux-resurrect-restore.service 2>/dev/null
        sudo rm -f /etc/systemd/system/tmux-resurrect-{save,restore}.service
        sudo systemctl daemon-reload
        echo "tmux-lives teardown: systemd units removed"
    end
    echo "tmux-lives teardown: done. (TPM plugins under ~/.tmux/plugins left in place.)"
end

function __tmux_lives_status_lines --description 'One status line per tmux-lives layer'
    set -l cat "$__fish_config_dir/functions/tmux-categorize.fish"
    set -l fragment "$HOME/.config/tmux/tmux-lives.conf"
    set -l r
    test -f "$__fish_config_dir/conf.d/tmux.fish"; and set -a r "OK conf.d/tmux.fish deployed"; or set -a r "MISSING conf.d/tmux.fish (fisher install …)"
    test -f $cat; and set -a r "OK categorizer deployed"; or set -a r "MISSING categorizer"
    test -f $fragment; and set -a r "OK tmux fragment present"; or set -a r "MISSING tmux fragment (run tmux-lives setup)"
    grep -qF -- "source-file $fragment" "$HOME/.tmux.conf" 2>/dev/null; and set -a r "OK ~/.tmux.conf sources fragment"; or set -a r "MISSING source-file line"
    test -d "$HOME/.tmux/plugins/tmux-resurrect"; and set -a r "OK tmux-resurrect present"; or set -a r "MISSING tmux-resurrect"
    if type -q systemctl
        systemctl is-enabled tmux-resurrect-save.service >/dev/null 2>&1; and set -a r "OK save service enabled"; or set -a r "MISSING save service (run tmux-lives setup)"
    else
        set -a r (__tmux_lives_persistence_status)
    end
    set -l pk (__tmux_lives_key tmux_lives_prefix_key S); test -n "$pk"; or set pk '(off)'
    set -l sk (__tmux_lives_key tmux_lives_switcher_key M-s); test -n "$sk"; or set sk '(off)'
    set -a r "OK switcher keys: prefix=$pk  no-prefix=$sk"
    set -l bc (__tmux_lives_key tmux_lives_bar_color ''); test -n "$bc"; or set bc '(none)'
    if test "$bc" = '(none)'
        set -a r "OK bar color: $bc"
    else
        set -l bdir lighter; test (__tmux_lives_key tmux_lives_status_invert 0) = 1; and set bdir darker
        set -a r "OK bar color: $bc (status bar: $bdir)"
    end
    set -l bf (__tmux_lives_baseline_path)
    test -e $bf; and set -a r "OK baseline $bf present"; or set -a r "OK baseline $bf (none yet)"
    printf '%s\n' $r
end

function __tmux_lives_help_hint --description 'Pointer to the tmux-lives help command'
    echo 'Run `tmux-lives` to see all commands.'
end

function __tmux_lives_box --argument-names title --description 'frame stdin lines in a rounded, orange-bordered box titled <title>'
    set -l ORG (printf '\e[38;5;208m')
    set -l RST (printf '\e[0m')
    set -l lines
    while read -l l
        set -a lines "$l"
    end
    # content-field width = widest line, measured in DISPLAY columns; at least wide
    # enough for the title that sits in the top edge
    set -l cw 0
    for l in $lines
        set -l w (string length --visible -- "$l")
        test $w -gt $cw; and set cw $w
    end
    set -l tw (string length --visible -- "$title")
    set -l tmin (math "$tw + 2")
    test $tmin -gt $cw; and set cw $tmin
    # top edge:  ╭─ <title> ─…─╮   (frame orange, title in the default fg)
    printf '%s╭─ %s%s%s %s╮%s\n' $ORG $RST "$title" $ORG (string repeat -n (math "$cw - $tw - 1") ─) $RST
    # content rows:  │ <line padded to cw> │
    # NB: pad goes through a quoted var — an inline (string repeat -n 0 …) yields ZERO
    # args (not one empty string), which would shift the trailing printf args.
    for l in $lines
        set -l pad (string repeat -n (math "$cw - "(string length --visible -- "$l")) ' ')
        printf '%s│%s %s%s %s│%s\n' $ORG $RST "$l" "$pad" $ORG $RST
    end
    # bottom edge:  ╰─…─╯
    printf '%s╰%s╯%s\n' $ORG (string repeat -n (math "$cw + 2") ─) $RST
end

function __tmux_lives_help_lines --description 'tmux-lives help content (unframed; alias-first columns)'
    printf '%s\n' \
        'categorized tmux sessions, switcher & persistence' \
        '' \
        'USAGE' \
        '  tmux-lives <command> [options]' \
        ''
    # alias-first rows — printf field widths align the columns (alias 2, command+args 28).
    # close keeps its `q` alias in the dispatcher but the help shows only `x`.
    printf '%-2s%-28s%s\n' '' 'setup <command> [options]' 'run `tmux-lives setup -h` for details'
    printf '%-2s%-28s%s\n' '' '' 'install · verify · teardown · keys · auto'
    printf '%-2s%-28s%s\n' u 'update' 'update the plugin (fisher update)'
    echo ''
    printf '%-2s%-28s%s\n' n 'new [name]' 'create a new session (optional name)'
    printf '%-2s%-28s%s\n' a 'attach <name> [-t]' 'attach to a session (-t takes it)'
    printf '%-2s%-28s%s\n' p 'picker [-t]' 'open the session switcher (-t takes it)'
    printf '%-2s%-28s%s\n' f 'fix' 'repair the SSH agent socket'
    printf '%-2s%-28s%s\n' c 'categorize' 're-categorize sessions (fix a bad name)'
    printf '%-2s%-28s%s\n' '' 'clear [-q|-x]' 'kill idle sessions (-q/-x also exits)'
    printf '%-2s%-28s%s\n' x 'close' 'kill the current session and exit'
end

function __tmux_lives_help --description 'tmux-lives command list'
    __tmux_lives_help_lines | __tmux_lives_box 'tmux-lives'
end

function __tmux_lives_keys_cmd --description 'tmux-lives setup keys [-p K] [-s K]'
    if test (count $argv) -eq 0
        echo "switcher keys: prefix="(__tmux_lives_key tmux_lives_prefix_key S)"  no-prefix="(__tmux_lives_key tmux_lives_switcher_key M-s)
        return 0
    end
    set -l changed 0
    while test (count $argv) -ge 2
        switch $argv[1]
            case -p --prefix-key
                set -U tmux_lives_prefix_key $argv[2]; set changed 1; set -e argv[1..2]
            case -s --switcher-key
                set -U tmux_lives_switcher_key $argv[2]; set changed 1; set -e argv[1..2]
            case --modal-key
                set -U tmux_lives_modal_key $argv[2]; set changed 1; set -e argv[1..2]
            case --scratch-key
                set -U tmux_lives_scratch_key $argv[2]; set changed 1; set -e argv[1..2]
            case --resize-key
                set -U tmux_lives_resize_key $argv[2]; set changed 1; set -e argv[1..2]
            case --status-pos-key
                set -U tmux_lives_status_pos_key $argv[2]; set changed 1; set -e argv[1..2]
            case --status-vis-key
                set -U tmux_lives_status_vis_key $argv[2]; set changed 1; set -e argv[1..2]
            case --theme-key
                set -U tmux_lives_theme_key $argv[2]; set changed 1; set -e argv[1..2]
            case '*'
                echo "tmux-lives setup keys: unknown option '$argv[1]'" >&2; return 1
        end
    end
    if test (count $argv) -gt 0
        echo "tmux-lives setup keys: incomplete option '$argv[1]'" >&2; return 1
    end
    test $changed -eq 1; and __tmux_lives_write_fragment
end

function __tmux_lives_seed_hex --argument-names css --description 'css color (#rrggbb / #rgb / rgb()) -> #rrggbb, lowercased; anything else (named colors, color(p3 ...)) -> nothing'
    set -l color (string lower -- "$css")
    test -n "$color"; or return
    set -l m (string match -rg '^#([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$' -- $color)
    if test (count $m) -eq 3
        echo $color
        return
    end
    set m (string match -rg '^#([0-9a-f])([0-9a-f])([0-9a-f])$' -- $color)
    if test (count $m) -eq 3
        echo "#$m[1]$m[1]$m[2]$m[2]$m[3]$m[3]"
        return
    end
    set m (string match -rg '^rgba?\(\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)' -- $color)
    if test (count $m) -eq 3
        set -l r $m[1]; set -l g $m[2]; set -l b $m[3]
        for v in r g b
            set -l x $$v
            test "$x" -gt 255; and set $v 255
        end
        printf '#%02x%02x%02x\n' $r $g $b
    end
end

function __tmux_lives_derive_status --description 'css color + invert(0/1) -> "bg=#rrggbb,fg=#rrggbb" for status-style; empty if unparseable'
    set -l invert $argv[2]
    set -l hexin (__tmux_lives_seed_hex $argv[1])
    test -n "$hexin"; or return
    set -l m (string match -rg '^#([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$' -- $hexin)
    set -l r (math "0x$m[1]"); set -l g (math "0x$m[2]"); set -l b (math "0x$m[3]")
    if test "$invert" = 1
        set r (math "round($r * 0.75)"); set g (math "round($g * 0.75)"); set b (math "round($b * 0.75)")
    else
        set r (math "round($r + (255 - $r) * 0.25)"); set g (math "round($g + (255 - $g) * 0.25)"); set b (math "round($b + (255 - $b) * 0.25)")
    end
    set -l hex (printf '#%02x%02x%02x' $r $g $b)
    # Tinted text (Light tint f=0.68): a hex shade of the bar's own hue, blended toward
    # white (dark bar) or black (light bar). Palette-independent; visible hue, still clearly
    # light/dark. fish `math` has no comparison operators -> integer luminance + test.
    set -l L (math "round(0.299 * $r + 0.587 * $g + 0.114 * $b)")
    set -l tr; set -l tg; set -l tb
    if test $L -gt 140
        set tr (math "round($r * 0.32)"); set tg (math "round($g * 0.32)"); set tb (math "round($b * 0.32)")
    else
        set tr (math "round($r + (255 - $r) * 0.68)"); set tg (math "round($g + (255 - $g) * 0.68)"); set tb (math "round($b + (255 - $b) * 0.68)")
    end
    echo "bg=$hex,fg="(printf '#%02x%02x%02x' $tr $tg $tb)
end

function __tmux_lives_derive_status_bg --description 'css color + invert -> just the bg hex of the derived status-style (empty if unparseable)'
    set -l ss (__tmux_lives_derive_status $argv[1] $argv[2])
    test -n "$ss"; or return 0
    string replace -rf '.*bg=([^,]+).*' '$1' -- $ss
end

# --- OKLCH conversion core (perceptual color space; feeds the v2 palette engine) ---
# sRGB <-> linear-light helpers (IEC 61966-2-1).
function __tmux_lives_lin_decode --argument c --description 'sRGB channel [0,1] -> linear-light (IEC 61966-2-1 EOTF)'
    if test $c -le 0.04045; math "$c / 12.92"; else; math "(($c + 0.055) / 1.055) ^ 2.4"; end
end
function __tmux_lives_lin_encode --argument c --description 'linear-light channel [0,1] -> sRGB (IEC 61966-2-1 OETF); c already clipped to [0,1]'
    if test $c -le 0.0031308; math "$c * 12.92"; else; math "1.055 * ($c ^ (1 / 2.4)) - 0.055"; end
end
function __tmux_lives_clip01 --argument v --description 'clamp a number into [0,1]'
    if test $v -lt 0; echo 0; return; end
    if test $v -gt 1; echo 1; return; end
    echo $v
end
function __tmux_lives_hex_to_rgb01 --argument hex --description '#rrggbb -> r,g,b (0-1) one per line'
    set -l h (string replace -r '^#' '' $hex)
    printf "%s\n" (math "0x"(string sub -s 1 -l 2 $h)"/255") (math "0x"(string sub -s 3 -l 2 $h)"/255") (math "0x"(string sub -s 5 -l 2 $h)"/255")
end
function __tmux_lives_linrgb_to_hex --argument r g b --description 'linear-light r,g,b (unclamped) -> #rrggbb (gamma-encode + clip01 + round)'
    set -l re (__tmux_lives_clip01 (__tmux_lives_lin_encode (__tmux_lives_clip01 $r)))
    set -l ge (__tmux_lives_clip01 (__tmux_lives_lin_encode (__tmux_lives_clip01 $g)))
    set -l be (__tmux_lives_clip01 (__tmux_lives_lin_encode (__tmux_lives_clip01 $b)))
    printf "#%02x%02x%02x\n" (math "round($re*255)") (math "round($ge*255)") (math "round($be*255)")
end
function __tmux_lives_rgb_to_oklch --argument r g b --description 'sRGB (0-1) -> OKLCH: prints L, C, H(deg 0-360) one per line'
    set -l rl (__tmux_lives_lin_decode $r); set -l gl (__tmux_lives_lin_decode $g); set -l bl (__tmux_lives_lin_decode $b)
    set -l l (math "0.4122214708*$rl + 0.5363325363*$gl + 0.0514459929*$bl")
    set -l m (math "0.2119034982*$rl + 0.6806995451*$gl + 0.1073969566*$bl")
    set -l s (math "0.0883024619*$rl + 0.2817188376*$gl + 0.6299787005*$bl")
    set -l lp (math "$l ^ (1/3)"); set -l mp (math "$m ^ (1/3)"); set -l sp (math "$s ^ (1/3)")
    set -l L (math "0.2104542553*$lp + 0.7936177850*$mp - 0.0040720468*$sp")
    set -l a (math "1.9779984951*$lp - 2.4285922050*$mp + 0.4505937099*$sp")
    set -l b (math "0.0259040371*$lp + 0.7827717662*$mp - 0.8086757660*$sp")
    set -l C (math "sqrt($a^2 + $b^2)")
    set -l H (math "atan2($b, $a) * 180 / $__tmux_lives_pi")
    if test $H -lt 0; set H (math "$H + 360"); end
    printf "%s\n" $L $C $H
end
function __tmux_lives_oklch_to_linrgb --argument L C H --description 'OKLCH -> linear r,g,b (unclamped) one per line'
    set -l Hrad (math "$H * $__tmux_lives_pi / 180")
    set -l a (math "$C * cos($Hrad)"); set -l b (math "$C * sin($Hrad)")
    set -l lp (math "$L + 0.3963377774*$a + 0.2158037573*$b")
    set -l mp (math "$L - 0.1055613458*$a - 0.0638541728*$b")
    set -l sp (math "$L - 0.0894841775*$a - 1.2914855480*$b")
    set -l l (math "$lp ^ 3"); set -l m (math "$mp ^ 3"); set -l s (math "$sp ^ 3")
    printf "%s\n" (math "4.0767416621*$l - 3.3077115913*$m + 0.2309699292*$s") (math "-1.2684380046*$l + 2.6097574011*$m - 0.3413193965*$s") (math "-0.0041960863*$l - 0.7034186147*$m + 1.7076147010*$s")
end
function __tmux_lives_in_gamut --argument r g b --description 'linear r,g,b each in [0,1]? -> 1/0'
    for v in $r $g $b
        if test $v -lt 0; echo 0; return; end
        if test $v -gt 1; echo 0; return; end
    end
    echo 1
end
function __tmux_lives_gamut_chroma --argument L H Ctarget --description 'max in-gamut chroma <= Ctarget (12-iter bisection)'
    set -l rgb (__tmux_lives_oklch_to_linrgb $L $Ctarget $H)
    if test (__tmux_lives_in_gamut $rgb[1] $rgb[2] $rgb[3]) -eq 1; echo $Ctarget; return; end
    set -l lo 0; set -l hi $Ctarget
    for i in (seq 1 12)
        set -l mid (math "($lo + $hi) / 2")
        set -l rgb2 (__tmux_lives_oklch_to_linrgb $L $mid $H)
        if test (__tmux_lives_in_gamut $rgb2[1] $rgb2[2] $rgb2[3]) -eq 1; set lo $mid; else; set hi $mid; end
    end
    echo $lo
end
function __tmux_lives_oklch_hex --argument L C H --description 'OKLCH -> #rrggbb (chroma gamut-clamped, gamma-encoded, clipped)'
    set -l Cg (__tmux_lives_gamut_chroma $L $H $C)
    set -l rgb (__tmux_lives_oklch_to_linrgb $L $Cg $H)
    __tmux_lives_linrgb_to_hex $rgb[1] $rgb[2] $rgb[3]
end
function __tmux_lives_norm360 --argument h --description 'wrap a hue in degrees into [0,360)'
    set -l hh $h
    while test $hh -lt 0; set hh (math "$hh + 360"); end
    while test $hh -ge 360; set hh (math "$hh - 360"); end
    echo $hh
end

function __tmux_lives_contrast_fg --argument-names hex --description 'bg hex -> readable fg via WCAG relative luminance: #111111 (light-ish bg) or #f5f5f5 (dark bg), crossover 0.179. Non-hex input (e.g. a tmux colourNNN fallback from a caller) -> #f5f5f5, matching v1s unparseable fallback.'
    set -l m (string match -rg '^#([0-9a-f]{6})$' -- (string lower -- $hex))
    test (count $m) -eq 1; or begin; echo '#f5f5f5'; return; end
    set -l rgb (__tmux_lives_hex_to_rgb01 $hex)
    set -l Lrel (math "0.2126*"(__tmux_lives_lin_decode $rgb[1])" + 0.7152*"(__tmux_lives_lin_decode $rgb[2])" + 0.0722*"(__tmux_lives_lin_decode $rgb[3]))
    if test $Lrel -gt 0.179; echo "#111111"; else; echo "#f5f5f5"; end
end

# --- theme engine v3 (gradient map): roles sample ONE hue-arc by lightness ---
# spec: docs/superpowers/specs/2026-07-16-theme-gradient-map-engine-design.md
# A theme = seed + scheme (arc) + phase (rotate) + knobs (cmax/range/shape/ease).
function __tmux_lives_theme_arc --argument-names scheme --description 'v3 scheme -> hue-arc offsets off the seed hue, two lines: start end (deg); unknown -> nothing'
    switch "$scheme"
        case mono;       printf '%s\n' 0 45
        case warm;       printf '%s\n' 8 -64
        case cool;       printf '%s\n' 60 -8
        case span;       printf '%s\n' 60 -60
        case wide;       printf '%s\n' 95 -75
        case aurora;     printf '%s\n' 120 30
        case sunset;     printf '%s\n' 150 -90
        case fire;       printf '%s\n' 130 -44
        case complement; printf '%s\n' 180 -30
        case full;       printf '%s\n' 0 360
    end
end

function __tmux_lives_theme_roles --description 'v3.1 support-role ladder, "<role> <t> <dL>" per line — THE one adjustable place (spec decision: keep tunable). bar (= the seed) and text (contrast side) are built in theme_palette, not here.'
    printf '%s\n' 'sep 0.15 0.06' 'tabs 0.30 0.10' 'active 0.50 0.15' 'windows 0.60 0.17' 'cap 0.80 0.22'
end

function __tmux_lives_theme_sample --argument-names t L seedH a0 a1 phase cs cmax shape ease --description 'sample the companion gradient at arc position t with ABSOLUTE lightness L: hue arc a0->a1 (+phase) off seedH, eased; chroma anchors at the seed (cs -> cmax sine arc; flat: cmax) -> #rrggbb'
    set -l et $t
    test "$ease" = cubic; and set et (math "$t ^ 3")
    set -l H (__tmux_lives_norm360 (math "$seedH + $a0 + ($a1 - $a0) * $et + $phase"))
    set -l C $cmax
    if test "$shape" != flat
        set C (math "$cs + ($cmax - $cs) * sin(3.141592653589793 * $t)")
    end
    __tmux_lives_oklch_hex $L $C $H
end

function __tmux_lives_theme_palette --argument-names seedHex scheme phase vividness shape ease contrast rotate --description 'seed + scheme/knobs -> 7 role hexes one per line (bar sep tabs active windows cap text). The bar IS the seed verbatim; companions cluster around it (gentle dL ladder, hue/chroma differentiate); text jumps to the contrast side. contrast auto|lighter|darker ('' = auto); rotate 0-4 permutes the COMPUTED support colors. Non-hex seed or unknown scheme -> nothing (callers fall back to legacy).'
    string match -qr '^#[0-9a-fA-F]{6}$' -- "$seedHex"; or return
    set -l arc (__tmux_lives_theme_arc "$scheme")
    test (count $arc) -eq 2; or return
    test -n "$phase"; or set phase 0
    test -n "$shape"; or set shape arc
    test -n "$ease"; or set ease linear
    test -n "$contrast"; or set contrast auto
    string match -qr '^[0-4]$' -- "$rotate"; or set rotate 0
    set -l cmax 0.105
    switch "$vividness"
        case soft;  set cmax 0.075
        case vivid; set cmax 0.130
    end
    set -l rgb (__tmux_lives_hex_to_rgb01 $seedHex)
    set -l ok (__tmux_lives_rgb_to_oklch $rgb[1] $rgb[2] $rgb[3])
    # direction: which side companions + text sit on. auto derives from the
    # seed's own lightness (dark seed -> lighter companions/text; light -> darker).
    set -l dir 1
    switch "$contrast"
        case darker
            set dir -1
        case lighter
            set dir 1
        case '*'   # auto
            test $ok[1] -ge 0.55; and set dir -1
    end
    # bar = the seed, verbatim (never re-derived through an OKLCH round-trip)
    printf '%s\n' (string lower -- $seedHex)
    set -l sup
    for rt in (__tmux_lives_theme_roles)
        set -l parts (string split ' ' $rt)
        set -l L (math "$ok[1] + $dir * $parts[3]")
        test $L -lt 0.05; and set L 0.05
        test $L -gt 0.95; and set L 0.95
        set -l hx (__tmux_lives_theme_sample $parts[2] $L $ok[3] $arc[1] $arc[2] $phase $ok[2] $cmax $shape $ease)
        test -n "$hx"; or return
        set -a sup $hx
    end
    # rotation: permute the COMPUTED support colors across the roles —
    # permuting the ladder params instead would be a no-op.
    for i in 1 2 3 4 5
        set -l j (math "(($i - 1 - $rotate) % 5 + 5) % 5 + 1")
        printf '%s\n' $sup[$j]
    end
    set -l Lt (math "$ok[1] + $dir * 0.45")
    test $Lt -lt 0.05; and set Lt 0.05
    test $Lt -gt 0.97; and set Lt 0.97
    __tmux_lives_oklch_hex $Lt 0.03 (__tmux_lives_norm360 (math "$ok[3] + $arc[2] + $phase"))
end

function __tmux_lives_color_cmd --description 'tmux-lives setup color [<css-color>] [-i|--invert] [-a|--apply]: ShellFish tab color + derived status bar; --apply reapplies the stored color live'
    set -l invert 0
    set -l color
    set -l have_color 0
    set -l apply 0
    for a in $argv
        switch $a
            case -i --invert
                set invert 1
            case -a --apply
                set apply 1
            case '*'
                set color $a; set have_color 1
        end
    end
    if test $apply -eq 1
        if test $have_color -eq 1
            echo "tmux-lives setup color: --apply takes no color argument" >&2
            return 1
        end
        set -l c (__tmux_lives_key tmux_lives_bar_color '')
        if test -z "$c"
            echo "tmux-lives: no seed set — set one with: tmux-lives setup color \"#rrggbb\"" >&2
            return 1
        end
        set -l _theme (__tmux_lives_key tmux_lives_theme mono)
        if test "$_theme" != off
            __tmux_lives_theme_apply_live
        else
            set -l ss (__tmux_lives_derive_status $c (__tmux_lives_key tmux_lives_status_invert 0))
            if test -n "$ss"
                if set -q tmux_lives_tmux_socket
                    command tmux -L $tmux_lives_tmux_socket set -g status-style $ss 2>/dev/null
                else
                    tmux set -g status-style $ss 2>/dev/null
                end
            end
        end
        set -l cat "$__fish_config_dir/functions/tmux-categorize.fish"
        test -f $cat; and fish --no-config $cat recolor $c 2>/dev/null
        echo "tmux-lives: reapplied seed $c"
        return 0
    end
    if test (count $argv) -eq 0
        set -l c (__tmux_lives_key tmux_lives_bar_color '')
        set -l dir lighter; test (__tmux_lives_key tmux_lives_status_invert 0) = 1; and set dir darker
        test -n "$c"; and echo "seed: $c (status bar: $dir)"; or echo "seed: (none)"
        return 0
    end
    if test $have_color -eq 0
        echo "tmux-lives setup color: -i needs a color, e.g. tmux-lives setup color \"#1f6feb\" -i" >&2
        return 1
    end
    if test -n "$color"; and string match -qr '[^A-Za-z0-9#(),./% -]' -- $color
        echo "tmux-lives setup color: invalid color '$color' — use a CSS color (red, #1f6feb, rgb(...), color(p3 ...))" >&2
        return 1
    end
    # Normalize a bare 3/6-digit hex to #rrggbb so __tmux_lives_derive_status (which
    # requires the leading #) can parse it; named colours / rgb()/color() are left alone.
    if string match -qr '^[0-9A-Fa-f]{3}$' -- $color; or string match -qr '^[0-9A-Fa-f]{6}$' -- $color
        set color "#$color"
    end
    set -U tmux_lives_bar_color $color
    set -U tmux_lives_status_invert $invert
    __tmux_lives_write_fragment
    # Re-emit the ShellFish OSC to attached clients now, so their tab colour updates
    # without waiting for the next client-attached. The emit logic lives in the categorizer.
    set -l cat "$__fish_config_dir/functions/tmux-categorize.fish"
    test -f $cat; and fish --no-config $cat recolor $color 2>/dev/null
    if test -n "$color"
        set -l dir lighter; test $invert -eq 1; and set dir darker
        echo "tmux-lives: seed set to $color (drives the theme + ShellFish tabs; status bar $dir)"
    else
        echo "tmux-lives: seed cleared"
    end
end

# --- theme engine v3: user surface -------------------------------------------
function __tmux_lives_theme_schemes --description 'the v3 scheme tokens, one per line — the ONE home of the list (CLI validation, list, picker batch all consume it)'
    printf '%s\n' mono warm cool span wide aurora sunset fire complement full
end

function __tmux_lives_theme_valid --argument-names token --description 'true if token is a v3 gradient-map scheme'
    contains -- "$token" (__tmux_lives_theme_schemes)
end

function __tmux_lives_theme_push --description 'internal: tmux set -g <option> <value> honoring the tmux_lives_tmux_socket test seam'
    if set -q tmux_lives_tmux_socket
        command tmux -L $tmux_lives_tmux_socket set -g $argv 2>/dev/null
    else
        tmux set -g $argv 2>/dev/null
    end
end

function __tmux_lives_theme_apply_live --description 'internal: push the effective v3 theme (or legacy when off/seedless) to the live server. With exactly 7 args (scheme phase viv shape ease contrast rotate) pushes THOSE values instead of the universals — the picker preview path; writes no state.'
    set -l theme; set -l phase; set -l viv; set -l shape; set -l ease; set -l contrast; set -l rotate
    if test (count $argv) -eq 7
        set theme $argv[1]; set phase $argv[2]; set viv $argv[3]; set shape $argv[4]
        set ease $argv[5]; set contrast $argv[6]; set rotate $argv[7]
    else
        set theme (__tmux_lives_key tmux_lives_theme mono)
        set phase (__tmux_lives_key tmux_lives_theme_phase 0)
        set viv (__tmux_lives_key tmux_lives_theme_vividness balanced)
        set shape (__tmux_lives_key tmux_lives_theme_shape arc)
        set ease (__tmux_lives_key tmux_lives_theme_ease linear)
        set contrast (__tmux_lives_key tmux_lives_theme_contrast auto)
        set rotate (__tmux_lives_key tmux_lives_theme_rotate 0)
    end
    set -l seed (__tmux_lives_seed_hex (__tmux_lives_key tmux_lives_bar_color ''))
    set -l tpal
    if test "$theme" != off; and test -n "$seed"
        set tpal (__tmux_lives_theme_palette $seed "$theme" $phase $viv $shape $ease $contrast $rotate)
    end
    if test (count $tpal) -eq 7
        __tmux_lives_theme_push status-style "bg=$tpal[1],fg=$tpal[5]"
        __tmux_lives_theme_push @tmux_lives_bar_bg $tpal[1]
        __tmux_lives_theme_push @tmux_lives_sep_fg $tpal[2]
        __tmux_lives_theme_push @tmux_lives_tabs_color $tpal[3]
        __tmux_lives_theme_push @tmux_lives_active_fg $tpal[4]
        __tmux_lives_theme_push @tmux_lives_cap_bg $tpal[6]
        __tmux_lives_theme_push @tmux_lives_cap_fg (__tmux_lives_contrast_fg $tpal[6])
        __tmux_lives_theme_push @tmux_lives_mark_fg $tpal[6]
        __tmux_lives_theme_push @tmux_lives_text_fg $tpal[7]
        return 0
    end
    # legacy (theme off, or no usable seed): derived bar + neutral cap + no-op role seeds
    set -l ss (__tmux_lives_derive_status (__tmux_lives_key tmux_lives_bar_color '') (__tmux_lives_key tmux_lives_status_invert 0))
    test -n "$ss"; and __tmux_lives_theme_push status-style $ss
    set -l barbg (__tmux_lives_derive_status_bg (__tmux_lives_key tmux_lives_bar_color '') (__tmux_lives_key tmux_lives_status_invert 0))
    test -n "$barbg"; or set barbg colour236
    __tmux_lives_theme_push @tmux_lives_bar_bg $barbg
    __tmux_lives_theme_push @tmux_lives_cap_bg colour238
    __tmux_lives_theme_push @tmux_lives_cap_fg (__tmux_lives_contrast_fg colour238)
    __tmux_lives_theme_push @tmux_lives_sep_fg default
    __tmux_lives_theme_push @tmux_lives_tabs_color ''
    __tmux_lives_theme_push @tmux_lives_active_fg default
    __tmux_lives_theme_push @tmux_lives_mark_fg default
    __tmux_lives_theme_push @tmux_lives_text_fg default
end

function __tmux_lives_theme_list --description 'tmux-lives setup theme list: every scheme + a 7-role gradient strip at the current seed/knobs'
    set -l seed (__tmux_lives_seed_hex (__tmux_lives_key tmux_lives_bar_color ''))
    test -n "$seed"; or set seed '#3a3a3a'   # no seed configured yet -> neutral so strips still render
    set -l phase (__tmux_lives_key tmux_lives_theme_phase 0)
    set -l viv (__tmux_lives_key tmux_lives_theme_vividness balanced)
    set -l shape (__tmux_lives_key tmux_lives_theme_shape arc)
    set -l ease (__tmux_lives_key tmux_lives_theme_ease linear)
    set -l contrast (__tmux_lives_key tmux_lives_theme_contrast auto)
    set -l rotate (__tmux_lives_key tmux_lives_theme_rotate 0)
    for scheme in (__tmux_lives_theme_schemes)
        set -l pal (__tmux_lives_theme_palette $seed $scheme $phase $viv $shape $ease $contrast $rotate)
        test (count $pal) -eq 7; or continue
        set -l strip
        for hex in $pal
            set -l m (string match -rg '^#([0-9a-fA-F]{2})([0-9a-fA-F]{2})([0-9a-fA-F]{2})$' -- $hex)
            test (count $m) -eq 3; or continue
            set -a strip (printf '\e[48;2;%d;%d;%dm  \e[0m' (math "0x$m[1]") (math "0x$m[2]") (math "0x$m[3]"))
        end
        printf '%s %-11s %s\n' (string join '' $strip) $scheme $pal[6]
    end
end

function __tmux_lives_theme_cmd --description 'tmux-lives setup theme [<scheme>|list|off] [--phase <deg>] [--vividness soft|balanced|vivid] [--shape arc|flat] [--ease linear|cubic] [--contrast auto|lighter|darker] [--rotate <0-4>]: the v3 gradient-map bar theme'
    if test (count $argv) -eq 0
        # inside tmux with display-popup: open the picker (the discovery surface);
        # otherwise print the current state.
        if set -q TMUX; and tmux list-commands 2>/dev/null | grep -q display-popup
            set -l cat "$__fish_config_dir/functions/tmux-categorize.fish"
            if test -f $cat
                set -l client (tmux display-message -p '#{client_name}' 2>/dev/null)
                tmux display-popup -B -E -w 52 -h 27 -- fish --no-config $cat theme-picker "$client"
                return 0
            end
        end
        set -l cur (__tmux_lives_key tmux_lives_theme mono)
        test "$cur" = off; and echo "theme: off (legacy bar colors)"; or echo "theme: $cur"
        set -l tphase (__tmux_lives_key tmux_lives_theme_phase 0)
        set -l tviv (__tmux_lives_key tmux_lives_theme_vividness balanced)
        set -l tshape (__tmux_lives_key tmux_lives_theme_shape arc)
        set -l tease (__tmux_lives_key tmux_lives_theme_ease linear)
        set -l tcon (__tmux_lives_key tmux_lives_theme_contrast auto)
        set -l trot (__tmux_lives_key tmux_lives_theme_rotate 0)
        echo "  phase: $tphase   vividness: $tviv   shape: $tshape   ease: $tease   contrast: $tcon   rotate: $trot"
        return 0
    end
    set -l scheme; set -l have_scheme 0
    set -l phase; set -l have_phase 0
    set -l viv; set -l have_viv 0
    set -l shape; set -l have_shape 0
    set -l ease; set -l have_ease 0
    set -l con; set -l have_con 0
    set -l rot; set -l have_rot 0
    set -l i 1
    while test $i -le (count $argv)
        switch $argv[$i]
            case list
                __tmux_lives_theme_list
                return
            case off
                set -U tmux_lives_theme off
                __tmux_lives_write_fragment
                __tmux_lives_theme_apply_live
                echo "tmux-lives: theme off — legacy bar colors (re-enable with 'tmux-lives setup theme mono')"
                return 0
            case --phase
                set i (math $i + 1); set phase $argv[$i]; set have_phase 1
            case --vividness
                set i (math $i + 1); set viv $argv[$i]; set have_viv 1
            case --shape
                set i (math $i + 1); set shape $argv[$i]; set have_shape 1
            case --ease
                set i (math $i + 1); set ease $argv[$i]; set have_ease 1
            case --contrast
                set i (math $i + 1); set con $argv[$i]; set have_con 1
            case --rotate
                set i (math $i + 1); set rot $argv[$i]; set have_rot 1
            case '*'
                set scheme $argv[$i]; set have_scheme 1
        end
        set i (math $i + 1)
    end
    # Validate everything before mutating any state (same contract as setup cap).
    if test $have_scheme -eq 1; and not __tmux_lives_theme_valid "$scheme"
        echo "tmux-lives setup theme: invalid scheme '$scheme' — valid: mono, warm, cool, span, wide, aurora, sunset, fire, complement, full (or: list, off)" >&2
        return 1
    end
    if test $have_phase -eq 1; and not string match -qr -- '^-?[0-9]+$' "$phase"
        echo "tmux-lives setup theme: invalid phase '$phase' — whole degrees, e.g. --phase -30" >&2
        return 1
    end
    test $have_phase -eq 1; and set phase (math "$phase % 360")
    if test $have_viv -eq 1
        switch "$viv"
            case soft balanced vivid
            case '*'
                echo "tmux-lives setup theme: invalid vividness '$viv' — valid: soft, balanced, vivid" >&2
                return 1
        end
    end
    if test $have_shape -eq 1
        switch "$shape"
            case arc flat
            case '*'
                echo "tmux-lives setup theme: invalid shape '$shape' — valid: arc, flat" >&2
                return 1
        end
    end
    if test $have_ease -eq 1
        switch "$ease"
            case linear cubic
            case '*'
                echo "tmux-lives setup theme: invalid ease '$ease' — valid: linear, cubic" >&2
                return 1
        end
    end
    if test $have_con -eq 1
        switch "$con"
            case auto lighter darker
            case '*'
                echo "tmux-lives setup theme: invalid contrast '$con' — valid: auto, lighter, darker" >&2
                return 1
        end
    end
    if test $have_rot -eq 1; and not string match -qr '^[0-4]$' -- "$rot"
        echo "tmux-lives setup theme: invalid rotate '$rot' — 0-4" >&2
        return 1
    end
    if test $have_scheme -eq 1
        set -l seed (__tmux_lives_seed_hex (__tmux_lives_key tmux_lives_bar_color ''))
        if test -z "$seed"
            echo "tmux-lives setup theme: no seed color — set one first: tmux-lives setup color '#rrggbb' (hex or rgb(); named colors have no derivable hue)" >&2
            return 1
        end
    end
    test $have_phase -eq 1; and set -U tmux_lives_theme_phase $phase
    test $have_viv -eq 1; and set -U tmux_lives_theme_vividness $viv
    test $have_shape -eq 1; and set -U tmux_lives_theme_shape $shape
    test $have_ease -eq 1; and set -U tmux_lives_theme_ease $ease
    test $have_con -eq 1; and set -U tmux_lives_theme_contrast $con
    test $have_rot -eq 1; and set -U tmux_lives_theme_rotate $rot
    test $have_scheme -eq 1; and set -U tmux_lives_theme $scheme
    # Persist into the fragment AND apply live (no reattach): write_fragment re-renders +
    # reloads; apply_live covers a server the reload can't reach (and the test seam).
    __tmux_lives_write_fragment
    __tmux_lives_theme_apply_live
    test $have_scheme -eq 1; and echo "tmux-lives: theme set to $scheme"
    test $have_phase -eq 1; and echo "tmux-lives: theme phase set to $phase"
    test $have_viv -eq 1; and echo "tmux-lives: theme vividness set to $viv"
    test $have_shape -eq 1; and echo "tmux-lives: theme shape set to $shape"
    test $have_ease -eq 1; and echo "tmux-lives: theme ease set to $ease"
    test $have_con -eq 1; and echo "tmux-lives: theme contrast set to $con"
    test $have_rot -eq 1; and echo "tmux-lives: theme rotate set to $rot"
end

function __tmux_lives_baseline_path --description 'path to the user-owned non-ShellFish baseline file (seam: tmux_lives_baseline_conf)'
    # Default mirrors __tcz_on_attach's baseline path in functions/tmux-categorize.fish — keep in sync.
    set -q tmux_lives_baseline_conf; and echo $tmux_lives_baseline_conf; or echo "$HOME/.tmux-lives.conf"
end

function __tmux_lives_state_path --description 'path to the machine-owned status-toggle state file (seam: tmux_lives_state_file)'
    # Default mirrors __tcz_write_state's inline path in functions/tmux-categorize.fish — keep in sync.
    set -q tmux_lives_state_file; and echo $tmux_lives_state_file; or echo "$HOME/.config/tmux/tmux-lives-state.conf"
end

function __tmux_lives_baseline_template --description 'print the default ~/.tmux-lives.conf (status-bar polish + non-ShellFish baseline)'
    printf '%s\n' \
        '# ~/.tmux-lives.conf — your general tmux-lives config.' \
        '# Sourced when tmux-lives loads (every client) and re-applied when a NON-ShellFish' \
        "# client attaches. Edit freely; 'tmux-lives setup conf reset' restores these defaults." \
        '' \
        '# --- status bar ---' \
        '# Layout (session name, window list, clock caps) is owned by the managed fragment via' \
        "# status-format[0]; tune it live with 'tmux set -g @tmux_lives_*'. This file only carries" \
        '# the clock content + its length, which the fragment renders inside the right cap.' \
        'set -g status-right-length 60' \
        '# status-right content goes through this var so tmux-lives keeps the categorize tick' \
        '# + continuum autosave attached (it sets the actual status-right). 12h, month-first:' \
        'set -g @tmux_lives_status_right "%b %-d · %-I:%M %p "' \
        '' \
        '# --- non-ShellFish baseline (re-applied when a non-ShellFish client attaches) ---' \
        "# Settings ShellFish's integration forces that you want undone for other clients." \
        '# Example:' \
        '# set -g mouse off'
end

function __tmux_lives_seed_baseline --argument-names f --description 'create the baseline file from the template iff absent (never overwrites)'
    test -e $f; and return 0
    __tmux_lives_baseline_template > $f
end

function __tmux_lives_conf_source --argument-names f --description 'source the user conf into tmux (honors the tmux_lives_tmux_socket test seam)'
    if set -q tmux_lives_tmux_socket
        command tmux -L $tmux_lives_tmux_socket source-file $f 2>/dev/null
    else
        tmux source-file $f 2>/dev/null
    end
end

function __tmux_lives_conf_cmd --description 'tmux-lives setup conf [edit|add <tmux-command>|reset]: manage ~/.tmux-lives.conf'
    set -l f (__tmux_lives_baseline_path)
    switch "$argv[1]"
        case ''
            echo "baseline file: $f"
            if test -e $f
                cat $f
            else
                echo "(does not exist yet — run 'tmux-lives setup conf edit' to create it)"
            end
        case edit
            __tmux_lives_seed_baseline $f
            set -l ed $EDITOR
            test -n "$ed"; or set ed vi
            $ed $f
        case add
            if test (count $argv) -lt 2
                echo "usage: tmux-lives setup conf add <tmux-command>" >&2
                return 1
            end
            __tmux_lives_seed_baseline $f
            printf '%s\n' (string join ' ' $argv[2..]) >> $f
            __tmux_lives_conf_source $f
            echo "tmux-lives: added to $f"
        case reset
            set -l backed 0
            test -e $f; and cp $f "$f.bak"; and set backed 1
            __tmux_lives_baseline_template > $f
            __tmux_lives_conf_source $f
            if test $backed -eq 1
                echo "tmux-lives: restored defaults to $f (previous version saved to $f.bak)"
            else
                echo "tmux-lives: wrote default $f"
            end
        case '*'
            echo "tmux-lives setup conf: unknown option '$argv[1]'" >&2
            echo "usage: tmux-lives setup conf [edit|add <tmux-command>|reset]" >&2
            return 1
    end
end

function __tmux_lives_setup_help_lines --description 'tmux-lives setup help content (unframed; tightened to fit an 80-col frame)'
    printf '%s\n' \
        'install & configuration' \
        '' \
        'install, i                  wire ~/.tmux.conf + plugins (systemd on Linux)' \
        'verify, v                   check install health + switcher keys' \
        'teardown                    remove the wiring (plugin & TPM kept)' \
        'keys                        show the current switcher keys' \
        "  -p, --prefix-key <key>    prefix-table bind (default: S; '' off)" \
        "  -s, --switcher-key <key>  no-prefix bind (default: M-s = Opt+s; '' off)" \
        "      --modal-key <key>     in-tmux command modal (default: M-m; '' off)" \
        "      --scratch-key <key>   scratch-split toggle (default: M-t; '' off)" \
        "      --resize-key <key>    scratch resize mode (default: M-r; '' off)" \
        "      --status-pos-key <key> status bar top/bottom (default: C-M-a; '' off)" \
        "      --status-vis-key <key> status bar hide/show  (default: C-M-s; '' off)" \
        "      --theme-key <key>     theme picker (default: M-k; '' off)" \
        'auto on|off|toggle|status   auto-attach to tmux on SSH login' \
        'color [<css>] [-i] [-a]     ShellFish tab/status; -i darker, -a reapply' \
        'theme [<scheme>|list|off]   gradient-map bar theme; no-arg=picker' \
        "      --phase <deg>         rotate the hue arc (default: 0)" \
        "      --vividness <v>       soft|balanced|vivid (default: balanced)" \
        "      --shape <s>           chroma arc|flat (default: arc)" \
        "      --ease <e>            hue easing linear|cubic (default: linear)" \
        "      --contrast <c>        companions auto|lighter|darker (default: auto)" \
        "      --rotate <n>          rotate companion placement 0-4 (default: 0)" \
        'conf [edit|add|reset]       manage ~/.tmux-lives.conf (reset=defaults)'
end

function __tmux_lives_setup_help --description 'tmux-lives setup command list'
    __tmux_lives_setup_help_lines | __tmux_lives_box 'tmux-lives setup'
end

function __tmux_lives_setup_dispatch
    switch "$argv[1]"
        case '' help -h --help
            __tmux_lives_setup_help
        case install i
            __tmux_lives_setup
        case verify v
            echo "tmux-lives verify:"
            __tmux_lives_status_lines | sed 's/^/  /'
        case teardown
            __tmux_lives_teardown
        case keys
            __tmux_lives_keys_cmd $argv[2..]
        case color
            __tmux_lives_color_cmd $argv[2..]
        case theme
            __tmux_lives_theme_cmd $argv[2..]
        case conf
            __tmux_lives_conf_cmd $argv[2..]
        case auto
            __tmux_lives_auto $argv[2..]
        case '*'
            echo "tmux-lives setup: unknown command '$argv[1]'" >&2
            __tmux_lives_setup_help >&2
            return 1
    end
end

function __tmux_lives_digest --description 'cksum over the given files (tmux-lives update change-detection)'
    cat $argv 2>/dev/null | cksum
end

function __tmux_lives_update --description 'Update the tmux-lives plugin via fisher; stay quiet unless something changed'
    if not type -q fisher
        echo 'tmux-lives update: fisher not found — install fisher, or update manually' >&2
        return 1
    end
    # installed plugin files to watch for changes (overridable in tests)
    set -l files $tmux_lives_update_files
    test -n "$files"; or set files \
        $__fish_config_dir/conf.d/tmux.fish \
        $__fish_config_dir/conf.d/tmux-lives-install.fish \
        $__fish_config_dir/functions/tmux-categorize.fish
    set -l before (__tmux_lives_digest $files)
    # fisher reinstalls (and is noisy) on every update — divert its output to a file
    # (a redirect, NOT a `(…)` capture: that would break fisher's background-job fetch)
    # and only surface it if something actually changed, or if it failed.
    set -l log (mktemp)
    set -g _tmux_lives_updating 1   # silence the generic post-update note; we report below
    fisher update bit-saver/tmux-lives >$log 2>&1
    set -l rc $status
    set -e _tmux_lives_updating
    if test $rc -ne 0
        cat $log >&2                # surface fisher's error
        rm -f $log
        return $rc
    end
    if test "$before" = (__tmux_lives_digest $files)
        echo 'tmux-lives: already up to date.'
    else
        cat $log                    # release fisher's output — something changed
        echo 'tmux-lives: updated — run `exec fish` to load the new version.'
    end
    rm -f $log
end

function tmux-lives --description 'tmux-lives: unified command — setup/update/new/attach/picker/fix/clear/close'
    set -l cmd $argv[1]
    switch "$cmd"
        case '' help -h --help
            __tmux_lives_help
        case picker p
            __tmux_lives_picker $argv[2..]
        case attach a
            __tmux_lives_attach $argv[2..]
        case new n
            __tmux_lives_new $argv[2..]
        case close x q
            __tmux_lives_close
        case clear
            __tmux_lives_clear $argv[2..]
        case fix f
            __tmux_lives_fix
        case update u
            __tmux_lives_update
        case categorize c
            __tmux_categorize
        case setup
            __tmux_lives_setup_dispatch $argv[2..]
        case install i verify v teardown keys auto color conf
            # hidden shortcut: setup subcommands also work at top level (kept out of help)
            __tmux_lives_setup_dispatch $argv
        case '*'
            echo "tmux-lives: unknown command '$cmd'" >&2
            __tmux_lives_help >&2
            return 1
    end
end

function _tmux_lives_post_install --on-event tmux-lives-install_install --description 'Post-install guidance'
    printf '%s\n' \
        '✓ tmux-lives installed. One command finishes setup:' \
        '    tmux-lives setup install' \
        '  (wires tmux + plugins, then reloads tmux). '(__tmux_lives_help_hint)
end

function __tmux_lives_fragment_path --description 'path to the generated managed fragment (seam: tmux_lives_fragment_file)'
    set -q tmux_lives_fragment_file; and echo $tmux_lives_fragment_file; or echo "$HOME/.config/tmux/tmux-lives.conf"
end

function __tmux_lives_migrate_v2 --description 'one-time v2 cap -> v3 theme universal migration (idempotent; runs on fisher update). Reset-to-mono policy: geometric schemes have no arc equivalent.'
    set -l oldscheme ''
    set -q tmux_lives_cap; and set oldscheme $tmux_lives_cap
    if set -q tmux_lives_cap_vividness; and not set -q tmux_lives_theme_vividness
        set -l v $tmux_lives_cap_vividness
        test "$v" = subtle; and set v soft
        contains -- $v soft balanced vivid; and set -U tmux_lives_theme_vividness $v
    end
    if set -q tmux_lives_cap_key; and not set -q tmux_lives_theme_key
        set -U tmux_lives_theme_key $tmux_lives_cap_key
    end
    for old in tmux_lives_cap tmux_lives_cap_vividness tmux_lives_cap_wheel tmux_lives_cap_role tmux_lives_cap_key
        set -q $old; and set -e $old
    end
    test -n "$oldscheme"; and echo "tmux-lives: cap scheme '$oldscheme' has no v3 equivalent — theme is mono; tune with 'tmux-lives setup theme'"
    return 0
end

function __tmux_lives_migrate_v31 --description 'v3 -> v3.1 seed-anchored migration: polarity/range have no v3.1 meaning (the bar IS the seed; contrast defaults auto) — erase them (idempotent)'
    set -l had 0
    for old in tmux_lives_theme_polarity tmux_lives_theme_range
        set -q $old; and begin; set -e $old; set had 1; end
    end
    test $had -eq 1; and echo "tmux-lives: theme is now seed-anchored — polarity/range retired; contrast defaults to auto ('tmux-lives setup theme')"
    return 0
end

function _tmux_lives_post_update --on-event tmux-lives-install_update --description 'Post-update: re-render the fragment (if set up) so new wiring lands, then note'
    # `fisher update` refreshes the plugin CODE but not the generated fragment. If this host
    # has been set up (the fragment exists), re-render it so new wiring (e.g. the client-attached
    # hook) lands without a manual `tmux-lives setup` — then reload tmux.
    __tmux_lives_migrate_v2
    __tmux_lives_migrate_v31
    set -l refreshed 0
    if test -e (__tmux_lives_fragment_path)
        __tmux_lives_write_fragment
        set refreshed 1
    end
    set -q _tmux_lives_updating; and return   # `tmux-lives update` reports the result itself
    if test $refreshed -eq 1
        printf '%s\n' '✓ tmux-lives updated — tmux config refreshed + reloaded; run `exec fish` for the new shell functions. '(__tmux_lives_help_hint)
    else
        printf '%s\n' '✓ tmux-lives updated — open a new shell (exec fish) to load it. '(__tmux_lives_help_hint)
    end
end
